In [1]:
from pathos_config import *

In [2]:
summary_table = load_data('iccs_summary_table', 'pathos_iccs_schema', connection)

In [3]:
# summary_table.groupby(['location', 'channel', 'occupation', 'income', 'age','gender']).emotional_engagement_score.mean().sort_values()

In [4]:
drivers_list = ['drivers_personalization_score', 'drivers_positivity_score', 'drivers_well_being_score', 'drivers_exciting_score', 'drivers_belonging_score', 'drivers_sustainability_score', 'drivers_security_score', 'drivers_convenience_score',
       'drivers_care_score', 'drivers_timeliness_score', 'drivers_respect_score', 'drivers_knowledge_score', 'drivers_fairness_score', 'drivers_channel_satisfaction_score', 'drivers_outcome_score', 'drivers_communication_score', 'drivers_ease_of_access_score', 'drivers_future_issues_score', 'drivers_competence_score', 'drivers_extra_mile_score', 'drivers_waiting_time_score', 'drivers_appeal_score', 'drivers_preferred_chanel_score', 'drivers_freshness_score', 'drivers_trust_score', 'drivers_regret_score', 'drivers_relationship_score', 'drivers_innovative_score', 'drivers_value_for_money_score', 'drivers_packaging_score']

# Top 3 Highest Negative Emotional Engagement Score by Location

In [5]:
def iccs_tree_top_province(*context):
    iccs_tree_province = summary_table.groupby(summary_table['location']).emotional_engagement_score.mean().sort_values().head(3)
    iccs_tree_province = iccs_tree_province.to_frame().reset_index()
    location_list = list(iccs_tree_province['location'])
    iccs_tree = pd.DataFrame(columns={ 'parent_id','id','name', 'driver_score'})
    iccs_tree.loc[0, ['name', 'id', 'parent_id', 'driver_score']] = ['ICCS', np.nan,np.nan, np.nan]
    num_list = [1,2,3]
    for i,j in zip(num_list,location_list):
        iccs_tree.loc[i, ['name', 'id', 'parent_id', 'driver_score']] = [j,np.nan,"1",iccs_tree_province.emotional_engagement_score[i-1]]
    for i in range(len(location_list)):
        sample_var = location_list[i]
        print(sample_var)
        vars()[sample_var] = summary_table.loc[summary_table['location']==location_list[i]]
        vars()[sample_var].dropna(axis=1, how='all', inplace=True)
        common_drivers = list(set(drivers_list).intersection(vars()[sample_var].columns))
        vars()[sample_var]= vars()[sample_var][common_drivers].mean().sort_values().head(3)
        vars()[sample_var] = vars()[sample_var].to_frame().reset_index()
        vars()[sample_var].reset_index(inplace=True)
        vars()[sample_var] = vars()[sample_var].drop(vars()[sample_var].columns[[0]], axis=1) 
        vars()[sample_var] = vars()[sample_var].rename(columns = {'index':'name', 0:'driver_score'})
        iccs_tree = iccs_tree.append(vars()[sample_var], ignore_index = True)
        iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))
    iccs_tree['parent_id'].iloc[4:7] = '2'
    iccs_tree['parent_id'].iloc[7:10] = '3'
    iccs_tree['parent_id'].iloc[10:13] = '4'
    return iccs_tree

In [7]:
iccs_tree_top_province = iccs_tree_top_province()

NameError: name 'summary_table_location' is not defined

In [ ]:
num_list = [1,2,3]
for i,j in zip(num_list,location_list):
    iccs_tree.loc[i, ['name', 'id', 'parent_id', 'emotional_engagement_score']] = [j, np.nan,'1',summary_table_location.emotional_engagement_score[i-1]]
iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))
location_dict = pd.Series(iccs_tree.id.values,index=iccs_tree.name).to_dict()

In [6]:
def iccs_tree_top_province(*context):
    iccs_tree_province = summary_table.groupby(summary_table['location']).emotional_engagement_score.mean().sort_values().head(3)
    iccs_tree_province = iccs_tree_province.to_frame().reset_index()
    location_list = list(iccs_tree_province['location'])
    iccs_tree = pd.DataFrame(columns={ 'parent_id','id','name', 'driver_score'})
    iccs_tree.loc[0, ['name', 'id', 'parent_id', 'driver_score']] = ['ICCS', np.nan,np.nan, np.nan]
    num_list = [1,2,3]
    for i,j in zip(num_list,location_list):
        iccs_tree.loc[i, ['name', 'id', 'parent_id', 'driver_score']] = [j,np.nan,"1",iccs_tree_province.emotional_engagement_score[i-1]]
    for i,j in zip(num_list,location_list):
        iccs_tree.loc[i, ['name', 'id', 'parent_id', 'emotional_engagement_score']] = [j, np.nan,'1',summary_table_location.emotional_engagement_score[i-1]]
        iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))
        location_dict = pd.Series(iccs_tree.id.values,index=iccs_tree.name).to_dict()
        print(location_dict)
    for i in range(len(location_list)):
        sample_var = location_list[i]
        print(sample_var)
        vars()[sample_var] = summary_table.loc[summary_table['location']==location_list[i]]
        vars()[sample_var].dropna(axis=1, how='all', inplace=True)
        common_drivers = list(set(drivers_list).intersection(vars()[sample_var].columns))
        vars()[sample_var]= vars()[sample_var][common_drivers].mean().sort_values().head(3)
        vars()[sample_var] = vars()[sample_var].to_frame().reset_index()
        vars()[sample_var].reset_index(inplace=True)
        vars()[sample_var] = vars()[sample_var].drop(vars()[sample_var].columns[[0]], axis=1) 
        vars()[sample_var] = vars()[sample_var].rename(columns = {'index':'name', 0:'driver_score'})
        vars()[sample_var]['parent_id'] = location_dict.get(sample_var_location)
        print(vars()[sample_var])
        iccs_tree = iccs_tree.append(vars()[sample_var], ignore_index = True)
        iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))
  
    return iccs_tree

In [ ]:
df_location_channel['parent_id'] = location_dict.get(sample_var_location)
    #print(df_location_channel) 
    df_channel = df_channel.append(df_location_channel, ignore_index = True)
df_channel.rename(columns= {'channel':'name'}, inplace=True)

iccs_tree = pd.concat([iccs_tree, df_channel], ignore_index=True)
iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))

In [7]:
iccs_tree_top_province

   driver_score parent_id  id                                name
0           NaN       NaN   1                                ICCS
1        -0.453         1   2                             Ontario
2        -0.413         1   3                            Manitoba
3        -0.392         1   4                                Peel
4        -0.484         2   5          drivers_waiting_time_score
5        -0.123         2   6            drivers_timeliness_score
6        -0.114         2   7         drivers_communication_score
7        -0.437         3   8          drivers_waiting_time_score
8        -0.166         3   9            drivers_timeliness_score
9        -0.117         3  10  drivers_channel_satisfaction_score
10       -0.367         4  11          drivers_waiting_time_score
11       -0.205         4  12            drivers_timeliness_score
12       -0.126         4  13            drivers_competence_score

# By Drivers

In [8]:
column_list = ['channel', 'age', 'occupation', 'gender','income', 'emotional_engagement_score']

In [9]:
df_channel = pd.DataFrame()
df_occupation = pd.DataFrame()
df_income = pd.DataFrame()
df_age = pd.DataFrame()

## Location + Channel

In [10]:
summary_table_location = summary_table.groupby(['location']).emotional_engagement_score.mean().sort_values().head(3)
summary_table_location = summary_table_location.to_frame().reset_index()
location_list = list(summary_table_location['location'])
iccs_tree = pd.DataFrame(columns={ 'parent_id','id','name', 'emotional_engagement_score'})

iccs_tree.loc[0, ['name', 'id', 'parent_id', 'emotional_engagement_score']] = ["ICCS", np.nan, np.nan, np.nan]

num_list = [1,2,3]
for i,j in zip(num_list,location_list):
    iccs_tree.loc[i, ['name', 'id', 'parent_id', 'emotional_engagement_score']] = [j, np.nan,'1',summary_table_location.emotional_engagement_score[i-1]]
iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))
location_dict = pd.Series(iccs_tree.id.values,index=iccs_tree.name).to_dict()
#print(location_dict)

df_channel = pd.DataFrame()
for i in range(len(location_list)):
    sample_var_location = location_list[i]
    print(sample_var_location)
    vars()[sample_var_location] = summary_table.loc[summary_table['location']==location_list[i]]
    vars()[sample_var_location] = vars()[sample_var_location][column_list]
    df_location_channel = vars()[sample_var_location].groupby(['channel']).emotional_engagement_score.mean().sort_values().head(3)
    df_location_channel = df_location_channel.to_frame().reset_index()
    df_location_channel['parent_id'] = location_dict.get(sample_var_location)
    #print(df_location_channel) 
    df_channel = df_channel.append(df_location_channel, ignore_index = True)
df_channel.rename(columns= {'channel':'name'}, inplace=True)

iccs_tree = pd.concat([iccs_tree, df_channel], ignore_index=True)
iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))

Ontario
Manitoba
Peel

In [11]:
iccs_tree

   parent_id  id emotional_engagement_score       name
0        NaN   1                        NaN       ICCS
1          1   2                     -0.453    Ontario
2          1   3                     -0.413   Manitoba
3          1   4                     -0.392       Peel
4          2   5                     -0.543  In-person
5          2   6                     -0.533  Telephone
6          2   7                     -0.250     Online
7          3   8                     -0.515     Online
8          3   9                     -0.397  Telephone
9          3  10                     -0.329  In-person
10         4  11                     -0.511  Telephone
11         4  12                     -0.352     Online
12         4  13                     -0.313  In-person

In [25]:
iccs_tree.parent_id.tail(1).values[0]+1

5

## Location + Channel + Occupation

In [46]:
summary_table_location = summary_table.groupby(['location']).emotional_engagement_score.mean().sort_values().head(3)
summary_table_location = summary_table_location.to_frame().reset_index()
location_list = list(summary_table_location['location'])


df_channel = pd.DataFrame()
df_occupation = pd.DataFrame()
for i in range(len(location_list)):
    sample_var_location = location_list[i]
    vars()[sample_var_location] = summary_table.loc[summary_table['location']==location_list[i]]
    vars()[sample_var_location] = vars()[sample_var_location][column_list]
    df_location_channel = vars()[sample_var_location].groupby(['channel']).emotional_engagement_score.mean().sort_values().head(3)
    df_location_channel = df_location_channel.to_frame().reset_index()
    channel_list = list(df_location_channel['channel'])
#     print(channel_list)
    for i in range(len(channel_list)):
        sample_var_channel = channel_list[i]
        vars()[sample_var_channel] = vars()[sample_var_location].loc[vars()[sample_var_location]['channel']==channel_list[i]]
        vars()[sample_var_channel] = vars()[sample_var_channel][column_list]
        df_channel_occupation = vars()[sample_var_channel].groupby(['occupation']).emotional_engagement_score.mean().sort_values().head(3)
        df_channel_occupation = df_channel_occupation.to_frame().reset_index()
        #print(df_channel_occupation)
        occupation_list = list(df_channel_occupation['occupation']) 
        print(occupation_list)
        parent_list = range(1001,1028)
        for i,j in zip(occupation_list, parent_list):
            df_channel_occupation['parent_id'] = j
            df_occupation = df_occupation.append(df_channel_occupation, ignore_index = False)
        #print(df_occupation)
df_occupation.rename(columns={'occupation':'name'}, inplace = True)

['Prefer not to answer', 'Paid employment, part time or full time', 'Retired']
['Paid employment, part time or full time', 'Other', 'Retired']
['Looking for work', 'Student, full or part time', 'Other']
['Paid employment, part time or full time', 'Homemaker', 'Retired']
['Paid employment, part time or full time', 'Other', 'Student, full or part time']
['Prefer not to answer', 'Other', 'Retired']
['Student, full or part time', 'Prefer not to answer', 'Paid employment, part time or full time']
['Other', 'Retired', 'Student, full or part time']
['Prefer not to answer', 'Retired', 'Looking for work']

In [47]:
parent_list = range(1001,1028)
parent_list[0]

1001

In [48]:
df_occupation

                                      name  emotional_engagement_score  parent_id
0                     Prefer not to answer                      -0.819       1001
1  Paid employment, part time or full time                      -0.629       1001
2                                  Retired                      -0.607       1001
0                     Prefer not to answer                      -0.819       1002
1  Paid employment, part time or full time                      -0.629       1002
2                                  Retired                      -0.607       1002
0                     Prefer not to answer                      -0.819       1003
1  Paid employment, part time or full time                      -0.629       1003
2                                  Retired                      -0.607       1003
0  Paid employment, part time or full time                      -0.795       1001
1                                    Other                      -0.741       1001
2                                  Retired                      -0.562       1001
0  Paid employment, part time or full time                      -0.795       1002
1                                    Other                      -0.741       1002
2                                  Retired                      -0.562       1002
0  Paid employment, part time or full time                      -0.795       1003
1                                    Other                      -0.741       1003
2                                  Retired                      -0.562       1003
0                         Looking for work                      -0.952       1001
1               Student, full or part time                      -0.752       1001
2                                    Other                      -0.307       1001
0                         Looking for work                      -0.952       1002
1               Student, full or part time                      -0.752       1002
2                                    Other                      -0.307       1002
0                         Looking for work                      -0.952       1003
1               Student, full or part time                      -0.752       1003
2                                    Other                      -0.307       1003
0  Paid employment, part time or full time                      -0.670       1001
1                                Homemaker                      -0.650       1001
2                                  Retired                      -0.569       1001
0  Paid employment, part time or full time                      -0.670       1002
1                                Homemaker                      -0.650       1002
2                                  Retired                      -0.569       1002
0  Paid employment, part time or full time                      -0.670       1003
1                                Homemaker                      -0.650       1003
2                                  Retired                      -0.569       1003
0  Paid employment, part time or full time                      -0.566       1001
1                                    Other                      -0.481       1001
2               Student, full or part time                      -0.461       1001
0  Paid employment, part time or full time                      -0.566       1002
1                                    Other                      -0.481       1002
2               Student, full or part time                      -0.461       1002
0  Paid employment, part time or full time                      -0.566       1003
1                                    Other                      -0.481       1003
2               Student, full or part time                      -0.461       1003
0                     Prefer not to answer                      -0.829       1001
1                                    Other                      -0.704       1001
2                                  Retired                      -0.611       1001
0                     Prefer not to answer                      -0.829       1002
1                                    Other                      -0.704       1002
2                                  Retired                      -0.611       1002
0                     Prefer not to answer                      -0.829       1003
1                                    Other                      -0.704       1003
2                                  Retired                      -0.611       1003
0               Student, full or part time                      -1.370       1001
1                     Prefer not to answer                      -0.684       1001
2  Paid employment, part time or full time                      -0.605       1001
0               Student, full or part time                      -1.370       1002
1                     Prefer not to answer                      -0.684       1002
2  Paid employment, part time or full time                      -0.605       1002
0               Student, full or part time                      -1.370       1003
1                     Prefer not to answer                      -0.684       1003
2  Paid employment, part time or full time                      -0.605       1003
0                                    Other                      -1.371       1001
1                                  Retired                      -0.692       1001
2               Student, full or part time                      -0.352       1001
0                                    Other                      -1.371       1002
1                                  Retired                      -0.692       1002
2               Student, full or part time                      -0.352       1002
0                                    Other                      -1.371       1003
1                                  Retired                      -0.692       1003
2               Student, full or part time                      -0.352       1003
0                     Prefer not to answer                      -1.530       1001
1                                  Retired                      -0.617       1001
2                         Looking for work                      -0.453       1001
0                     Prefer not to answer                      -1.530       1002
1                                  Retired                      -0.617       1002
2                         Looking for work                      -0.453       1002
0                     Prefer not to answer                      -1.530       1003
1                                  Retired                      -0.617       1003
2                         Looking for work                      -0.453       1003

In [70]:
iccs_tree = pd.concat([iccs_tree, df_occupation], ignore_index=True)
iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))
# iccs_tree['parent_id'].iloc[14:17] = '5'
# iccs_tree['parent_id'].iloc[17:20] = '6'
# iccs_tree['parent_id'].iloc[20:23] = '7'
# iccs_tree['parent_id'].iloc[23:26] = '8'
# iccs_tree['parent_id'].iloc[26:29] = '9'
# iccs_tree['parent_id'].iloc[29:32] = '10'
# iccs_tree['parent_id'].iloc[32:36] = '11'
# iccs_tree['parent_id'].iloc[36:39] = '12'
# iccs_tree['parent_id'].iloc[39:42] = '13'

In [18]:
iccs_tree

   parent_id  id emotional_engagement_score       name
0        NaN   1                        NaN       ICCS
1          1   2                     -0.453    Ontario
2          1   3                     -0.413   Manitoba
3          1   4                     -0.392       Peel
4          2   5                     -0.543  In-person
5          2   6                     -0.533  Telephone
6          2   7                     -0.250     Online
7          3   8                     -0.515     Online
8          3   9                     -0.397  Telephone
9          3  10                     -0.329  In-person
10         4  11                     -0.511  Telephone
11         4  12                     -0.352     Online
12         4  13                     -0.313  In-person

In [85]:
summary_table_location = summary_table.groupby(['location']).emotional_engagement_score.mean().sort_values().head(3)
summary_table_location = summary_table_location.to_frame().reset_index()
location_list = list(summary_table_location['location'])
# iccs_tree = pd.DataFrame(columns={ 'parent_id','id','name', 'emotional_engagement_score'})
# iccs_tree.loc[0] = [np.nan,np.nan,'ICCS', np.nan]

# num_list = [1,2,3]
# for i,j in zip(num_list,location_list):
#     iccs_tree.loc[i] = ["1",summary_table_location.emotional_engagement_score[i-1],j,np.nan]

df_channel = pd.DataFrame()
df_occupation = pd.DataFrame()
df_income = pd.DataFrame()
for i in range(len(location_list)):
    sample_var_location = location_list[i]
    vars()[sample_var_location] = summary_table.loc[summary_table['location']==location_list[i]]
    vars()[sample_var_location] = vars()[sample_var_location][column_list]
    df_location_channel = vars()[sample_var_location].groupby(['channel']).emotional_engagement_score.mean().sort_values().head(3)
    df_location_channel = df_location_channel.to_frame().reset_index()
    channel_list = list(df_location_channel['channel'])
#     print(channel_list)
    for i in range(len(channel_list)):
        sample_var_channel = channel_list[i]
        vars()[sample_var_channel] = vars()[sample_var_location].loc[vars()[sample_var_location]['channel']==channel_list[i]]
        vars()[sample_var_channel] = vars()[sample_var_channel][column_list]
        df_channel_occupation = vars()[sample_var_channel].groupby(['occupation']).emotional_engagement_score.mean().sort_values().head(3)
        df_channel_occupation = df_channel_occupation.to_frame().reset_index()
        #print(df_channel_occupation)
        occupation_list = list(df_channel_occupation['occupation'])
#         print(occupation_list)
        #df_occupation = df_occupation.append(df_channel_occupation, ignore_index = True)
        
        for i in range(len(occupation_list)):
            sample_var_occupation = occupation_list[i]
            print(sample_var_occupation)
            vars()[sample_var_occupation] = vars()[sample_var_channel].loc[vars()[sample_var_channel]['occupation']==occupation_list[i]]
            vars()[sample_var_occupation] = vars()[sample_var_occupation][column_list]
            df_occupation_income = vars()[sample_var_occupation].groupby(['income']).emotional_engagement_score.mean().sort_values().head(3)
            df_occupation_income = df_occupation_income.to_frame().reset_index()
            print(df_occupation_income)
            income_list = list(df_occupation_income['income'])
            #print(income_list)
            df_income = df_income.append(df_occupation_income, ignore_index = False)
            df_income = df_income.append(['new dataframe'], ignore_index = False)
        #print(df_income)
df_income.rename(columns={'income':'name'}, inplace = True)

Prefer not to answer
                 income  emotional_engagement_score
0  Prefer not to answer                      -0.819
Paid employment, part time or full time
                income  emotional_engagement_score
0   $70,000 to $89,999                      -0.943
1   $30,000 to $49,999                      -0.920
2  $90,000 to $109,999                      -0.626
Retired
                income  emotional_engagement_score
0   $20,000 to $29,999                      -1.283
1  $90,000 to $109,999                      -1.143
2   $30,000 to $49,999                      -1.135
Paid employment, part time or full time
                 income  emotional_engagement_score
0      $150,000 or more                      -1.027
1  $110,000 to $149,999                      -0.905
2    $30,000 to $49,999                      -0.808
Other
               income  emotional_engagement_score
0  $10,000 to $19,999                      -1.482
1  $30,000 to $49,999                       0.000
Retired
                 income  emotional_engagement_score
0      $150,000 or more                      -1.411
1  $110,000 to $149,999                      -1.389
2    $30,000 to $49,999                      -0.657
Looking for work
               income  emotional_engagement_score
0       Under $10,000                      -1.575
1  $50,000 to $69,999                      -0.036
2  $20,000 to $29,999                       0.000
Student, full or part time
               income  emotional_engagement_score
0       Under $10,000                      -1.374
1    $150,000 or more                      -1.289
2  $30,000 to $49,999                      -1.057
Other
                 income  emotional_engagement_score
0    $50,000 to $69,999                      -1.141
1    $10,000 to $19,999                      -0.710
2  $110,000 to $149,999                       0.000
Paid employment, part time or full time
                 income  emotional_engagement_score
0    $30,000 to $49,999                      -1.280
1         Under $10,000                      -1.164
2  $110,000 to $149,999                      -0.934
Homemaker
                 income  emotional_engagement_score
0    $20,000 to $29,999                      -1.506
1  Prefer not to answer                      -0.222
Retired
               income  emotional_engagement_score
0  $10,000 to $19,999                      -1.512
1  $50,000 to $69,999                      -1.050
2  $70,000 to $89,999                      -0.241
Paid employment, part time or full time
                 income  emotional_engagement_score
0      $150,000 or more                      -1.213
1  Prefer not to answer                      -0.959
2  $110,000 to $149,999                      -0.800
Other
                income  emotional_engagement_score
0   $30,000 to $49,999                      -1.222
1  $90,000 to $109,999                      -0.942
2   $50,000 to $69,999                      -0.242
Student, full or part time
                 income  emotional_engagement_score
0  $110,000 to $149,999                      -1.385
1    $50,000 to $69,999                      -0.685
2    $30,000 to $49,999                      -0.349
Prefer not to answer
               income  emotional_engagement_score
0  $30,000 to $49,999                      -1.486
1  $10,000 to $19,999                      -0.171
Other
                 income  emotional_engagement_score
0    $50,000 to $69,999                      -1.575
1  $110,000 to $149,999                      -1.473
2    $10,000 to $19,999                      -0.730
Retired
                income  emotional_engagement_score
0        Under $10,000                      -2.067
1  $90,000 to $109,999                      -1.737
2     $150,000 or more                      -1.500
Student, full or part time
                 income  emotional_engagement_score
0    $30,000 to $49,999                      -2.454
1  Prefer not to answer                      -1.573
2         Under $10,000                      -1.409
Prefer not to answer
                 income  emotional_engagement_score
0    $50,000 to $69,999                      -1.368
1  Prefer not to answer                       0.000
Paid employment, part time or full time
                 income  emotional_engagement_score
0  Prefer not to answer                      -1.394
1      $150,000 or more                      -1.239
2    $50,000 to $69,999                      -1.058
Other
               income  emotional_engagement_score
0  $30,000 to $49,999                      -2.521
1  $20,000 to $29,999                      -0.796
Retired
               income  emotional_engagement_score
0  $70,000 to $89,999                      -1.775
1  $30,000 to $49,999                      -1.409
2  $50,000 to $69,999                      -0.211
Student, full or part time
               income  emotional_engagement_score
0  $20,000 to $29,999                      -0.592
1  $50,000 to $69,999                      -0.407
2  $10,000 to $19,999                       0.000
Prefer not to answer
                 income  emotional_engagement_score
0  Prefer not to answer                      -1.530
Retired
                 income  emotional_engagement_score
0  Prefer not to answer                      -1.555
1      $150,000 or more                      -1.096
2   $90,000 to $109,999                      -0.611
Looking for work
               income  emotional_engagement_score
0  $50,000 to $69,999                      -2.631
1    $150,000 or more                      -1.107
2  $10,000 to $19,999                       0.815

In [86]:
df_income

               0  emotional_engagement_score                  name
0            NaN                      -0.819  Prefer not to answer
0  new dataframe                         NaN                   NaN
0            NaN                      -0.943    $70,000 to $89,999
1            NaN                      -0.920    $30,000 to $49,999
2            NaN                      -0.626   $90,000 to $109,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.283    $20,000 to $29,999
1            NaN                      -1.143   $90,000 to $109,999
2            NaN                      -1.135    $30,000 to $49,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.027      $150,000 or more
1            NaN                      -0.905  $110,000 to $149,999
2            NaN                      -0.808    $30,000 to $49,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.482    $10,000 to $19,999
1            NaN                       0.000    $30,000 to $49,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.411      $150,000 or more
1            NaN                      -1.389  $110,000 to $149,999
2            NaN                      -0.657    $30,000 to $49,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.575         Under $10,000
1            NaN                      -0.036    $50,000 to $69,999
2            NaN                       0.000    $20,000 to $29,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.374         Under $10,000
1            NaN                      -1.289      $150,000 or more
2            NaN                      -1.057    $30,000 to $49,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.141    $50,000 to $69,999
1            NaN                      -0.710    $10,000 to $19,999
2            NaN                       0.000  $110,000 to $149,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.280    $30,000 to $49,999
1            NaN                      -1.164         Under $10,000
2            NaN                      -0.934  $110,000 to $149,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.506    $20,000 to $29,999
1            NaN                      -0.222  Prefer not to answer
0  new dataframe                         NaN                   NaN
0            NaN                      -1.512    $10,000 to $19,999
1            NaN                      -1.050    $50,000 to $69,999
2            NaN                      -0.241    $70,000 to $89,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.213      $150,000 or more
1            NaN                      -0.959  Prefer not to answer
2            NaN                      -0.800  $110,000 to $149,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.222    $30,000 to $49,999
1            NaN                      -0.942   $90,000 to $109,999
2            NaN                      -0.242    $50,000 to $69,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.385  $110,000 to $149,999
1            NaN                      -0.685    $50,000 to $69,999
2            NaN                      -0.349    $30,000 to $49,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.486    $30,000 to $49,999
1            NaN                      -0.171    $10,000 to $19,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.575    $50,000 to $69,999
1            NaN                      -1.473  $110,000 to $149,999
2            NaN                      -0.730    $10,000 to $19,999
0  new dataframe                         NaN                   NaN
0            NaN                      -2.067         Under $10,000
1            NaN                      -1.737   $90,000 to $109,999
2            NaN                      -1.500      $150,000 or more
0  new dataframe                         NaN                   NaN
0            NaN                      -2.454    $30,000 to $49,999
1            NaN                      -1.573  Prefer not to answer
2            NaN                      -1.409         Under $10,000
0  new dataframe                         NaN                   NaN
0            NaN                      -1.368    $50,000 to $69,999
1            NaN                       0.000  Prefer not to answer
0  new dataframe                         NaN                   NaN
0            NaN                      -1.394  Prefer not to answer
1            NaN                      -1.239      $150,000 or more
2            NaN                      -1.058    $50,000 to $69,999
0  new dataframe                         NaN                   NaN
0            NaN                      -2.521    $30,000 to $49,999
1            NaN                      -0.796    $20,000 to $29,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.775    $70,000 to $89,999
1            NaN                      -1.409    $30,000 to $49,999
2            NaN                      -0.211    $50,000 to $69,999
0  new dataframe                         NaN                   NaN
0            NaN                      -0.592    $20,000 to $29,999
1            NaN                      -0.407    $50,000 to $69,999
2            NaN                       0.000    $10,000 to $19,999
0  new dataframe                         NaN                   NaN
0            NaN                      -1.530  Prefer not to answer
0  new dataframe                         NaN                   NaN
0            NaN                      -1.555  Prefer not to answer
1            NaN                      -1.096      $150,000 or more
2            NaN                      -0.611   $90,000 to $109,999
0  new dataframe                         NaN                   NaN
0            NaN                      -2.631    $50,000 to $69,999
1            NaN                      -1.107      $150,000 or more
2            NaN                       0.815    $10,000 to $19,999
0  new dataframe                         NaN                   NaN

In [89]:
iccs_tree = pd.concat([iccs_tree, df_income], ignore_index=True)
iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))
# iccs_tree['parent_id'].iloc[14:17] = '5'
# iccs_tree['parent_id'].iloc[17:20] = '6'
# iccs_tree['parent_id'].iloc[20:23] = '7'
# iccs_tree['parent_id'].iloc[23:26] = '8'
# iccs_tree['parent_id'].iloc[26:29] = '9'
# iccs_tree['parent_id'].iloc[29:32] = '10'
# iccs_tree['parent_id'].iloc[32:36] = '11'
# iccs_tree['parent_id'].iloc[36:39] = '12'
# iccs_tree['parent_id'].iloc[39:42] = '13'

In [90]:
iccs_tree

                                        name emotional_engagement_score   id parent_id              0
0                                        NaN                       ICCS    1       NaN            NaN
1                                    Ontario                        NaN    2    -0.453            NaN
2                                   Manitoba                        NaN    3    -0.413            NaN
3                                       Peel                        NaN    4    -0.392            NaN
4                                  In-person                     -0.543    5         2            NaN
5                                  Telephone                     -0.533    6         2            NaN
6                                     Online                     -0.250    7         2            NaN
7                                     Online                     -0.515    8         3            NaN
8                                  Telephone                     -0.397    9         3            NaN
9                                  In-person                     -0.329   10         3            NaN
10                                 Telephone                     -0.511   11         4            NaN
11                                    Online                     -0.352   12         4            NaN
12                                 In-person                     -0.313   13         4            NaN
13                      Prefer not to answer                     -0.819   14       NaN            NaN
14   Paid employment, part time or full time                     -0.629   15       NaN            NaN
15                                   Retired                     -0.607   16       NaN            NaN
16   Paid employment, part time or full time                     -0.795   17       NaN            NaN
17                                     Other                     -0.741   18       NaN            NaN
18                                   Retired                     -0.562   19       NaN            NaN
19                          Looking for work                     -0.952   20       NaN            NaN
20                Student, full or part time                     -0.752   21       NaN            NaN
21                                     Other                     -0.307   22       NaN            NaN
22   Paid employment, part time or full time                     -0.670   23       NaN            NaN
23                                 Homemaker                     -0.650   24       NaN            NaN
24                                   Retired                     -0.569   25       NaN            NaN
25   Paid employment, part time or full time                     -0.566   26       NaN            NaN
26                                     Other                     -0.481   27       NaN            NaN
27                Student, full or part time                     -0.461   28       NaN            NaN
28                      Prefer not to answer                     -0.829   29       NaN            NaN
29                                     Other                     -0.704   30       NaN            NaN
30                                   Retired                     -0.611   31       NaN            NaN
31                Student, full or part time                     -1.370   32       NaN            NaN
32                      Prefer not to answer                     -0.684   33       NaN            NaN
33   Paid employment, part time or full time                     -0.605   34       NaN            NaN
34                                     Other                     -1.371   35       NaN            NaN
35                                   Retired                     -0.692   36       NaN            NaN
36                Student, full or part time                     -0.352   37       NaN            NaN
37                      Prefer not to answer                     -1.530   38       NaN            NaN
38                                   Retired                     -0.617   39       NaN            NaN
39                          Looking for work                     -0.453   40       NaN            NaN
40                      Prefer not to answer                     -0.819   41       NaN            NaN
41                                       NaN                        NaN   42       NaN  new dataframe
42                        $70,000 to $89,999                     -0.943   43       NaN            NaN
43                        $30,000 to $49,999                     -0.920   44       NaN            NaN
44                       $90,000 to $109,999                     -0.626   45       NaN            NaN
45                                       NaN                        NaN   46       NaN  new dataframe
46                        $20,000 to $29,999                     -1.283   47       NaN            NaN
47                       $90,000 to $109,999                     -1.143   48       NaN            NaN
48                        $30,000 to $49,999                     -1.135   49       NaN            NaN
49                                       NaN                        NaN   50       NaN  new dataframe
50                          $150,000 or more                     -1.027   51       NaN            NaN
51                      $110,000 to $149,999                     -0.905   52       NaN            NaN
52                        $30,000 to $49,999                     -0.808   53       NaN            NaN
53                                       NaN                        NaN   54       NaN  new dataframe
54                        $10,000 to $19,999                     -1.482   55       NaN            NaN
55                        $30,000 to $49,999                      0.000   56       NaN            NaN
56                                       NaN                        NaN   57       NaN  new dataframe
57                          $150,000 or more                     -1.411   58       NaN            NaN
58                      $110,000 to $149,999                     -1.389   59       NaN            NaN
59                        $30,000 to $49,999                     -0.657   60       NaN            NaN
60                                       NaN                        NaN   61       NaN  new dataframe
61                             Under $10,000                     -1.575   62       NaN            NaN
62                        $50,000 to $69,999                     -0.036   63       NaN            NaN
63                        $20,000 to $29,999                      0.000   64       NaN            NaN
64                                       NaN                        NaN   65       NaN  new dataframe
65                             Under $10,000                     -1.374   66       NaN            NaN
66                          $150,000 or more                     -1.289   67       NaN            NaN
67                        $30,000 to $49,999                     -1.057   68       NaN            NaN
68                                       NaN                        NaN   69       NaN  new dataframe
69                        $50,000 to $69,999                     -1.141   70       NaN            NaN
70                        $10,000 to $19,999                     -0.710   71       NaN            NaN
71                      $110,000 to $149,999                      0.000   72       NaN            NaN
72                                       NaN                        NaN   73       NaN  new dataframe
73                        $30,000 to $49,999                     -1.280   74       NaN            NaN
74                             Under $10,000                     -1.164   75       NaN            NaN
75                      $110,000 to $149,999                     -0.934   76       NaN            NaN
76                                       NaN                        NaN   77       NaN  new dataframe
77                        $20,000 to $29,999                     -1.506   78       NaN            NaN
78                      Prefer not to answer                     -0.222   79       NaN            NaN
79                                       NaN                        NaN   80       NaN  new dataframe
80                        $10,000 to $19,999                     -1.512   81       NaN            NaN
81                        $50,000 to $69,999                     -1.050   82       NaN            NaN
82                        $70,000 to $89,999                     -0.241   83       NaN            NaN
83                                       NaN                        NaN   84       NaN  new dataframe
84                          $150,000 or more                     -1.213   85       NaN            NaN
85                      Prefer not to answer                     -0.959   86       NaN            NaN
86                      $110,000 to $149,999                     -0.800   87       NaN            NaN
87                                       NaN                        NaN   88       NaN  new dataframe
88                        $30,000 to $49,999                     -1.222   89       NaN            NaN
89                       $90,000 to $109,999                     -0.942   90       NaN            NaN
90                        $50,000 to $69,999                     -0.242   91       NaN            NaN
91                                       NaN                        NaN   92       NaN  new dataframe
92                      $110,000 to $149,999                     -1.385   93       NaN            NaN
93                        $50,000 to $69,999                     -0.685   94       NaN            NaN
94                        $30,000 to $49,999                     -0.349   95       NaN            NaN
95                                       NaN                        NaN   96       NaN  new dataframe
96                        $30,000 to $49,999                     -1.486   97       NaN            NaN
97                        $10,000 to $19,999                     -0.171   98       NaN            NaN
98                                       NaN                        NaN   99       NaN  new dataframe
99                        $50,000 to $69,999                     -1.575  100       NaN            NaN
100                     $110,000 to $149,999                     -1.473  101       NaN            NaN
101                       $10,000 to $19,999                     -0.730  102       NaN            NaN
102                                      NaN                        NaN  103       NaN  new dataframe
103                            Under $10,000                     -2.067  104       NaN            NaN
104                      $90,000 to $109,999                     -1.737  105       NaN            NaN
105                         $150,000 or more                     -1.500  106       NaN            NaN
106                                      NaN                        NaN  107       NaN  new dataframe
107                       $30,000 to $49,999                     -2.454  108       NaN            NaN
108                     Prefer not to answer                     -1.573  109       NaN            NaN
109                            Under $10,000                     -1.409  110       NaN            NaN
110                                      NaN                        NaN  111       NaN  new dataframe
111                       $50,000 to $69,999                     -1.368  112       NaN            NaN
112                     Prefer not to answer                      0.000  113       NaN            NaN
113                                      NaN                        NaN  114       NaN  new dataframe
114                     Prefer not to answer                     -1.394  115       NaN            NaN
115                         $150,000 or more                     -1.239  116       NaN            NaN
116                       $50,000 to $69,999                     -1.058  117       NaN            NaN
117                                      NaN                        NaN  118       NaN  new dataframe
118                       $30,000 to $49,999                     -2.521  119       NaN            NaN
119                       $20,000 to $29,999                     -0.796  120       NaN            NaN
120                                      NaN                        NaN  121       NaN  new dataframe
121                       $70,000 to $89,999                     -1.775  122       NaN            NaN
122                       $30,000 to $49,999                     -1.409  123       NaN            NaN
123                       $50,000 to $69,999                     -0.211  124       NaN            NaN
124                                      NaN                        NaN  125       NaN  new dataframe
125                       $20,000 to $29,999                     -0.592  126       NaN            NaN
126                       $50,000 to $69,999                     -0.407  127       NaN            NaN
127                       $10,000 to $19,999                      0.000  128       NaN            NaN
128                                      NaN                        NaN  129       NaN  new dataframe
129                     Prefer not to answer                     -1.530  130       NaN            NaN
130                                      NaN                        NaN  131       NaN  new dataframe
131                     Prefer not to answer                     -1.555  132       NaN            NaN
132                         $150,000 or more                     -1.096  133       NaN            NaN
133                      $90,000 to $109,999                     -0.611  134       NaN            NaN
134                                      NaN                        NaN  135       NaN  new dataframe
135                       $50,000 to $69,999                     -2.631  136       NaN            NaN
136                         $150,000 or more                     -1.107  137       NaN            NaN
137                       $10,000 to $19,999                      0.815  138       NaN            NaN
138                                      NaN                        NaN  139       NaN  new dataframe

In [93]:
summary_table_location = summary_table.groupby(['location']).emotional_engagement_score.mean().sort_values().head(3)
summary_table_location = summary_table_location.to_frame().reset_index()
location_list = list(summary_table_location['location'])
# iccs_tree = pd.DataFrame(columns={ 'parent_id','id','name', 'emotional_engagement_score'})
# iccs_tree.loc[0] = [np.nan,np.nan,'ICCS', np.nan]

# num_list = [1,2,3]
# for i,j in zip(num_list,location_list):
#     iccs_tree.loc[i] = ["1",summary_table_location.emotional_engagement_score[i-1],j,np.nan]


for i in range(len(location_list)):
    sample_var_location = location_list[i]
    vars()[sample_var_location] = summary_table.loc[summary_table['location']==location_list[i]]
    vars()[sample_var_location] = vars()[sample_var_location][column_list]
    df_location_channel = vars()[sample_var_location].groupby(['channel']).emotional_engagement_score.mean().sort_values().head(3)
    df_location_channel = df_location_channel.to_frame().reset_index()
    channel_list = list(df_location_channel['channel'])
#     print(channel_list)
    for i in range(len(channel_list)):
        sample_var_channel = channel_list[i]
        vars()[sample_var_channel] = vars()[sample_var_location].loc[vars()[sample_var_location]['channel']==channel_list[i]]
        vars()[sample_var_channel] = vars()[sample_var_channel][column_list]
        df_channel_occupation = vars()[sample_var_channel].groupby(['occupation']).emotional_engagement_score.mean().sort_values().head(3)
        df_channel_occupation = df_channel_occupation.to_frame().reset_index()
        #print(df_channel_occupation)
        occupation_list = list(df_channel_occupation['occupation'])
#         print(occupation_list)
        #df_occupation = df_occupation.append(df_channel_occupation, ignore_index = True)
        
        for i in range(len(occupation_list)):
            sample_var_occupation = occupation_list[i]
            print(sample_var_occupation)
            vars()[sample_var_occupation] = vars()[sample_var_channel].loc[vars()[sample_var_channel]['occupation']==occupation_list[i]]
            vars()[sample_var_occupation] = vars()[sample_var_occupation][column_list]
            df_occupation_income = vars()[sample_var_occupation].groupby(['income']).emotional_engagement_score.mean().sort_values().head(3)
            df_occupation_income = df_occupation_income.to_frame().reset_index()
            #print(df_occupation_income)
            income_list = list(df_occupation_income['income'])
            #print(income_list)
            for i in range(len(income_list)):
                sample_var_income = income_list[i]
                print(sample_var_income)
                vars()[sample_var_income] = vars()[sample_var_occupation].loc[vars()[sample_var_occupation]['occupation']==occupation_list[i]]
                vars()[sample_var_income] = vars()[sample_var_income][column_list]
                df_income_age = vars()[sample_var_income].groupby(['age']).emotional_engagement_score.mean().sort_values().head(3)
                df_income_age = df_income_age.to_frame().reset_index()
                #print(df_occupation_income)
                age_list = list(df_income_age['age'])
                df_age = df_age.append(df_income_age, ignore_index = False)
                df_age = df_age.append(['new dataframe'], ignore_index = False)
        #print(df_income)
df_age.rename(columns={'age':'name'}, inplace = True)

Prefer not to answer
Prefer not to answer
Paid employment, part time or full time
$70,000 to $89,999
$30,000 to $49,999
$90,000 to $109,999
Retired
$20,000 to $29,999
$90,000 to $109,999
$30,000 to $49,999
Paid employment, part time or full time
$150,000 or more
$110,000 to $149,999
$30,000 to $49,999
Other
$10,000 to $19,999
$30,000 to $49,999
Retired
$150,000 or more
$110,000 to $149,999
$30,000 to $49,999
Looking for work
Under $10,000
$50,000 to $69,999
$20,000 to $29,999
Student, full or part time
Under $10,000
$150,000 or more
$30,000 to $49,999
Other
$50,000 to $69,999
$10,000 to $19,999
$110,000 to $149,999
Paid employment, part time or full time
$30,000 to $49,999
Under $10,000
$110,000 to $149,999
Homemaker
$20,000 to $29,999
Prefer not to answer
Retired
$10,000 to $19,999
$50,000 to $69,999
$70,000 to $89,999
Paid employment, part time or full time
$150,000 or more
Prefer not to answer
$110,000 to $149,999
Other
$30,000 to $49,999
$90,000 to $109,999
$50,000 to $69,999
Student, full or part time
$110,000 to $149,999
$50,000 to $69,999
$30,000 to $49,999
Prefer not to answer
$30,000 to $49,999
$10,000 to $19,999
Other
$50,000 to $69,999
$110,000 to $149,999
$10,000 to $19,999
Retired
Under $10,000
$90,000 to $109,999
$150,000 or more
Student, full or part time
$30,000 to $49,999
Prefer not to answer
Under $10,000
Prefer not to answer
$50,000 to $69,999
Prefer not to answer
Paid employment, part time or full time
Prefer not to answer
$150,000 or more
$50,000 to $69,999
Other
$30,000 to $49,999
$20,000 to $29,999
Retired
$70,000 to $89,999
$30,000 to $49,999
$50,000 to $69,999
Student, full or part time
$20,000 to $29,999
$50,000 to $69,999
$10,000 to $19,999
Prefer not to answer
Prefer not to answer
Retired
Prefer not to answer
$150,000 or more
$90,000 to $109,999
Looking for work
$50,000 to $69,999
$150,000 or more
$10,000 to $19,999

In [94]:
print(df_age)

          name  emotional_engagement_score              0
0  45-54 years                      -0.819            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  18-24 years                      -1.033            NaN
1  35-44 years                      -0.949            NaN
2  55-64 years                      -0.618            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  65-74 years                      -0.640            NaN
1  55-64 years                      -0.603            NaN
2  45-54 years                       0.000            NaN
0          NaN                         NaN  new dataframe
0  18-24 years                      -1.365            NaN
1  55-64 years                      -1.307            NaN
2  45-54 years                      -0.700            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  45-54 years                      -0.741            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  55-64 years                      -0.594            NaN
1  65-74 years                      -0.545            NaN
0          NaN                         NaN  new dataframe
0  45-54 years                      -1.409            NaN
1  25-34 years                      -0.867            NaN
2  55-64 years                      -0.809            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  18-24 years                      -1.025            NaN
1  25-34 years                       0.884            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  35-44 years                      -0.710            NaN
1  55-64 years                      -0.570            NaN
2  45-54 years                       0.000            NaN
0          NaN                         NaN  new dataframe
0  18-24 years                      -0.866            NaN
1  45-54 years                      -0.770            NaN
2  35-44 years                      -0.748            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  55-64 years                      -1.506            NaN
1  35-44 years                      -0.444            NaN
2  25-34 years                       0.000            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  65-74 years                      -0.814            NaN
1  55-64 years                      -0.243            NaN
0          NaN                         NaN  new dataframe
0  55-64 years                      -0.908            NaN
1  65-74 years                      -0.581            NaN
2  45-54 years                      -0.572            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  25-34 years                      -0.942            NaN
1  55-64 years                      -0.729            NaN
2  35-44 years                      -0.630            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  18-24 years                      -0.553            NaN
1  25-34 years                       0.000            NaN
0          NaN                         NaN  new dataframe
0  25-34 years                      -1.486            NaN
1  45-54 years                      -0.171            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  45-54 years                      -1.575            NaN
1  55-64 years                      -0.868            NaN
2  25-34 years                      -0.104            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  55-64 years                      -1.056            NaN
1  65-74 years                      -0.373            NaN
2  45-54 years                       0.325            NaN
0          NaN                         NaN  new dataframe
0  45-54 years                      -2.454            NaN
1  25-34 years                      -1.491            NaN
2  18-24 years                      -0.706            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  18-24 years                      -1.368            NaN
1  55-64 years                       0.000            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  65-74 years                      -1.530            NaN
1  35-44 years                      -0.811            NaN
2  25-34 years                      -0.601            NaN
0          NaN                         NaN  new dataframe
0  25-34 years                      -2.521            NaN
1  45-54 years                      -0.796            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  55-64 years                      -1.693            NaN
1  45-54 years                      -0.457            NaN
2  65-74 years                       0.076            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  18-24 years                      -0.396            NaN
1  25-34 years                      -0.219            NaN
0          NaN                         NaN  new dataframe
0  25-34 years                      -1.530            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  65-74 years                      -0.702            NaN
1  55-64 years                      -0.470            NaN
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0          NaN                         NaN  new dataframe
0  25-34 years                      -2.631            NaN
1  55-64 years                       0.001            NaN
2  18-24 years                       0.815            NaN
0          NaN                         NaN  new dataframe

In [95]:
iccs_tree = pd.concat([iccs_tree, df_age], ignore_index=True)
iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))

In [96]:
iccs_tree

                                        name emotional_engagement_score   id parent_id              0
0                                        NaN                       ICCS    1       NaN            NaN
1                                    Ontario                        NaN    2    -0.453            NaN
2                                   Manitoba                        NaN    3    -0.413            NaN
3                                       Peel                        NaN    4    -0.392            NaN
4                                  In-person                     -0.543    5         2            NaN
5                                  Telephone                     -0.533    6         2            NaN
6                                     Online                     -0.250    7         2            NaN
7                                     Online                     -0.515    8         3            NaN
8                                  Telephone                     -0.397    9         3            NaN
9                                  In-person                     -0.329   10         3            NaN
10                                 Telephone                     -0.511   11         4            NaN
11                                    Online                     -0.352   12         4            NaN
12                                 In-person                     -0.313   13         4            NaN
13                      Prefer not to answer                     -0.819   14       NaN            NaN
14   Paid employment, part time or full time                     -0.629   15       NaN            NaN
15                                   Retired                     -0.607   16       NaN            NaN
16   Paid employment, part time or full time                     -0.795   17       NaN            NaN
17                                     Other                     -0.741   18       NaN            NaN
18                                   Retired                     -0.562   19       NaN            NaN
19                          Looking for work                     -0.952   20       NaN            NaN
20                Student, full or part time                     -0.752   21       NaN            NaN
21                                     Other                     -0.307   22       NaN            NaN
22   Paid employment, part time or full time                     -0.670   23       NaN            NaN
23                                 Homemaker                     -0.650   24       NaN            NaN
24                                   Retired                     -0.569   25       NaN            NaN
25   Paid employment, part time or full time                     -0.566   26       NaN            NaN
26                                     Other                     -0.481   27       NaN            NaN
27                Student, full or part time                     -0.461   28       NaN            NaN
28                      Prefer not to answer                     -0.829   29       NaN            NaN
29                                     Other                     -0.704   30       NaN            NaN
30                                   Retired                     -0.611   31       NaN            NaN
31                Student, full or part time                     -1.370   32       NaN            NaN
32                      Prefer not to answer                     -0.684   33       NaN            NaN
33   Paid employment, part time or full time                     -0.605   34       NaN            NaN
34                                     Other                     -1.371   35       NaN            NaN
35                                   Retired                     -0.692   36       NaN            NaN
36                Student, full or part time                     -0.352   37       NaN            NaN
37                      Prefer not to answer                     -1.530   38       NaN            NaN
38                                   Retired                     -0.617   39       NaN            NaN
39                          Looking for work                     -0.453   40       NaN            NaN
40                      Prefer not to answer                     -0.819   41       NaN            NaN
41                                       NaN                        NaN   42       NaN  new dataframe
42                        $70,000 to $89,999                     -0.943   43       NaN            NaN
43                        $30,000 to $49,999                     -0.920   44       NaN            NaN
44                       $90,000 to $109,999                     -0.626   45       NaN            NaN
45                                       NaN                        NaN   46       NaN  new dataframe
46                        $20,000 to $29,999                     -1.283   47       NaN            NaN
47                       $90,000 to $109,999                     -1.143   48       NaN            NaN
48                        $30,000 to $49,999                     -1.135   49       NaN            NaN
49                                       NaN                        NaN   50       NaN  new dataframe
50                          $150,000 or more                     -1.027   51       NaN            NaN
51                      $110,000 to $149,999                     -0.905   52       NaN            NaN
52                        $30,000 to $49,999                     -0.808   53       NaN            NaN
53                                       NaN                        NaN   54       NaN  new dataframe
54                        $10,000 to $19,999                     -1.482   55       NaN            NaN
55                        $30,000 to $49,999                      0.000   56       NaN            NaN
56                                       NaN                        NaN   57       NaN  new dataframe
57                          $150,000 or more                     -1.411   58       NaN            NaN
58                      $110,000 to $149,999                     -1.389   59       NaN            NaN
59                        $30,000 to $49,999                     -0.657   60       NaN            NaN
60                                       NaN                        NaN   61       NaN  new dataframe
61                             Under $10,000                     -1.575   62       NaN            NaN
62                        $50,000 to $69,999                     -0.036   63       NaN            NaN
63                        $20,000 to $29,999                      0.000   64       NaN            NaN
64                                       NaN                        NaN   65       NaN  new dataframe
65                             Under $10,000                     -1.374   66       NaN            NaN
66                          $150,000 or more                     -1.289   67       NaN            NaN
67                        $30,000 to $49,999                     -1.057   68       NaN            NaN
68                                       NaN                        NaN   69       NaN  new dataframe
69                        $50,000 to $69,999                     -1.141   70       NaN            NaN
70                        $10,000 to $19,999                     -0.710   71       NaN            NaN
71                      $110,000 to $149,999                      0.000   72       NaN            NaN
72                                       NaN                        NaN   73       NaN  new dataframe
73                        $30,000 to $49,999                     -1.280   74       NaN            NaN
74                             Under $10,000                     -1.164   75       NaN            NaN
75                      $110,000 to $149,999                     -0.934   76       NaN            NaN
76                                       NaN                        NaN   77       NaN  new dataframe
77                        $20,000 to $29,999                     -1.506   78       NaN            NaN
78                      Prefer not to answer                     -0.222   79       NaN            NaN
79                                       NaN                        NaN   80       NaN  new dataframe
80                        $10,000 to $19,999                     -1.512   81       NaN            NaN
81                        $50,000 to $69,999                     -1.050   82       NaN            NaN
82                        $70,000 to $89,999                     -0.241   83       NaN            NaN
83                                       NaN                        NaN   84       NaN  new dataframe
84                          $150,000 or more                     -1.213   85       NaN            NaN
85                      Prefer not to answer                     -0.959   86       NaN            NaN
86                      $110,000 to $149,999                     -0.800   87       NaN            NaN
87                                       NaN                        NaN   88       NaN  new dataframe
88                        $30,000 to $49,999                     -1.222   89       NaN            NaN
89                       $90,000 to $109,999                     -0.942   90       NaN            NaN
90                        $50,000 to $69,999                     -0.242   91       NaN            NaN
91                                       NaN                        NaN   92       NaN  new dataframe
92                      $110,000 to $149,999                     -1.385   93       NaN            NaN
93                        $50,000 to $69,999                     -0.685   94       NaN            NaN
94                        $30,000 to $49,999                     -0.349   95       NaN            NaN
95                                       NaN                        NaN   96       NaN  new dataframe
96                        $30,000 to $49,999                     -1.486   97       NaN            NaN
97                        $10,000 to $19,999                     -0.171   98       NaN            NaN
98                                       NaN                        NaN   99       NaN  new dataframe
99                        $50,000 to $69,999                     -1.575  100       NaN            NaN
100                     $110,000 to $149,999                     -1.473  101       NaN            NaN
101                       $10,000 to $19,999                     -0.730  102       NaN            NaN
102                                      NaN                        NaN  103       NaN  new dataframe
103                            Under $10,000                     -2.067  104       NaN            NaN
104                      $90,000 to $109,999                     -1.737  105       NaN            NaN
105                         $150,000 or more                     -1.500  106       NaN            NaN
106                                      NaN                        NaN  107       NaN  new dataframe
107                       $30,000 to $49,999                     -2.454  108       NaN            NaN
108                     Prefer not to answer                     -1.573  109       NaN            NaN
109                            Under $10,000                     -1.409  110       NaN            NaN
110                                      NaN                        NaN  111       NaN  new dataframe
111                       $50,000 to $69,999                     -1.368  112       NaN            NaN
112                     Prefer not to answer                      0.000  113       NaN            NaN
113                                      NaN                        NaN  114       NaN  new dataframe
114                     Prefer not to answer                     -1.394  115       NaN            NaN
115                         $150,000 or more                     -1.239  116       NaN            NaN
116                       $50,000 to $69,999                     -1.058  117       NaN            NaN
117                                      NaN                        NaN  118       NaN  new dataframe
118                       $30,000 to $49,999                     -2.521  119       NaN            NaN
119                       $20,000 to $29,999                     -0.796  120       NaN            NaN
120                                      NaN                        NaN  121       NaN  new dataframe
121                       $70,000 to $89,999                     -1.775  122       NaN            NaN
122                       $30,000 to $49,999                     -1.409  123       NaN            NaN
123                       $50,000 to $69,999                     -0.211  124       NaN            NaN
124                                      NaN                        NaN  125       NaN  new dataframe
125                       $20,000 to $29,999                     -0.592  126       NaN            NaN
126                       $50,000 to $69,999                     -0.407  127       NaN            NaN
127                       $10,000 to $19,999                      0.000  128       NaN            NaN
128                                      NaN                        NaN  129       NaN  new dataframe
129                     Prefer not to answer                     -1.530  130       NaN            NaN
130                                      NaN                        NaN  131       NaN  new dataframe
131                     Prefer not to answer                     -1.555  132       NaN            NaN
132                         $150,000 or more                     -1.096  133       NaN            NaN
133                      $90,000 to $109,999                     -0.611  134       NaN            NaN
134                                      NaN                        NaN  135       NaN  new dataframe
135                       $50,000 to $69,999                     -2.631  136       NaN            NaN
136                         $150,000 or more                     -1.107  137       NaN            NaN
137                       $10,000 to $19,999                      0.815  138       NaN            NaN
138                                      NaN                        NaN  139       NaN  new dataframe
139                              45-54 years                     -0.819  140       NaN            NaN
140                                      NaN                        NaN  141       NaN  new dataframe
141                                      NaN                        NaN  142       NaN  new dataframe
142                              18-24 years                     -1.033  143       NaN            NaN
143                              35-44 years                     -0.949  144       NaN            NaN
144                              55-64 years                     -0.618  145       NaN            NaN
145                                      NaN                        NaN  146       NaN  new dataframe
146                                      NaN                        NaN  147       NaN  new dataframe
147                                      NaN                        NaN  148       NaN  new dataframe
148                                      NaN                        NaN  149       NaN  new dataframe
149                              65-74 years                     -0.640  150       NaN            NaN
150                              55-64 years                     -0.603  151       NaN            NaN
151                              45-54 years                      0.000  152       NaN            NaN
152                                      NaN                        NaN  153       NaN  new dataframe
153                              18-24 years                     -1.365  154       NaN            NaN
154                              55-64 years                     -1.307  155       NaN            NaN
155                              45-54 years                     -0.700  156       NaN            NaN
156                                      NaN                        NaN  157       NaN  new dataframe
157                                      NaN                        NaN  158       NaN  new dataframe
158                                      NaN                        NaN  159       NaN  new dataframe
159                                      NaN                        NaN  160       NaN  new dataframe
160                              45-54 years                     -0.741  161       NaN            NaN
161                                      NaN                        NaN  162       NaN  new dataframe
162                                      NaN                        NaN  163       NaN  new dataframe
163                                      NaN                        NaN  164       NaN  new dataframe
164                              55-64 years                     -0.594  165       NaN            NaN
165                              65-74 years                     -0.545  166       NaN            NaN
166                                      NaN                        NaN  167       NaN  new dataframe
167                              45-54 years                     -1.409  168       NaN            NaN
168                              25-34 years                     -0.867  169       NaN            NaN
169                              55-64 years                     -0.809  170       NaN            NaN
170                                      NaN                        NaN  171       NaN  new dataframe
171                                      NaN                        NaN  172       NaN  new dataframe
172                                      NaN                        NaN  173       NaN  new dataframe
173                                      NaN                        NaN  174       NaN  new dataframe
174                              18-24 years                     -1.025  175       NaN            NaN
175                              25-34 years                      0.884  176       NaN            NaN
176                                      NaN                        NaN  177       NaN  new dataframe
177                                      NaN                        NaN  178       NaN  new dataframe
178                                      NaN                        NaN  179       NaN  new dataframe
179                                      NaN                        NaN  180       NaN  new dataframe
180                              35-44 years                     -0.710  181       NaN            NaN
181                              55-64 years                     -0.570  182       NaN            NaN
182                              45-54 years                      0.000  183       NaN            NaN
183                                      NaN                        NaN  184       NaN  new dataframe
184                              18-24 years                     -0.866  185       NaN            NaN
185                              45-54 years                     -0.770  186       NaN            NaN
186                              35-44 years                     -0.748  187       NaN            NaN
187                                      NaN                        NaN  188       NaN  new dataframe
188                                      NaN                        NaN  189       NaN  new dataframe
189                                      NaN                        NaN  190       NaN  new dataframe
190                                      NaN                        NaN  191       NaN  new dataframe
191                              55-64 years                     -1.506  192       NaN            NaN
192                              35-44 years                     -0.444  193       NaN            NaN
193                              25-34 years                      0.000  194       NaN            NaN
194                                      NaN                        NaN  195       NaN  new dataframe

In [104]:
summary_table_location = summary_table.groupby(['location']).emotional_engagement_score.mean().sort_values().head(3)
summary_table_location = summary_table_location.to_frame().reset_index()
location_list = list(summary_table_location['location'])
# iccs_tree = pd.DataFrame(columns={ 'parent_id','id','name', 'emotional_engagement_score'})
# iccs_tree.loc[0] = [np.nan,np.nan,'ICCS', np.nan]

# num_list = [1,2,3]
# for i,j in zip(num_list,location_list):
#     iccs_tree.loc[i] = ["1",summary_table_location.emotional_engagement_score[i-1],j,np.nan]

df_channel = pd.DataFrame()
df_occupation = pd.DataFrame()
df_income = pd.DataFrame()
df_age = pd.DataFrame()
df_gender = pd.DataFrame()
for i in range(len(location_list)):
    sample_var_location = location_list[i]
    vars()[sample_var_location] = summary_table.loc[summary_table['location']==location_list[i]]
    vars()[sample_var_location] = vars()[sample_var_location][column_list]
    df_location_channel = vars()[sample_var_location].groupby(['channel']).emotional_engagement_score.mean().sort_values().head(3)
    df_location_channel = df_location_channel.to_frame().reset_index()
    channel_list = list(df_location_channel['channel'])
#     print(channel_list)
    for i in range(len(channel_list)):
        sample_var_channel = channel_list[i]
        vars()[sample_var_channel] = vars()[sample_var_location].loc[vars()[sample_var_location]['channel']==channel_list[i]]
        vars()[sample_var_channel] = vars()[sample_var_channel][column_list]
        df_channel_occupation = vars()[sample_var_channel].groupby(['occupation']).emotional_engagement_score.mean().sort_values().head(3)
        df_channel_occupation = df_channel_occupation.to_frame().reset_index()
        #print(df_channel_occupation)
        occupation_list = list(df_channel_occupation['occupation'])
#         print(occupation_list)
        #df_occupation = df_occupation.append(df_channel_occupation, ignore_index = True)
        
        for i in range(len(occupation_list)):
            sample_var_occupation = occupation_list[i]
            print(sample_var_occupation)
            vars()[sample_var_occupation] = vars()[sample_var_channel].loc[vars()[sample_var_channel]['occupation']==occupation_list[i]]
            vars()[sample_var_occupation] = vars()[sample_var_occupation][column_list]
            df_occupation_income = vars()[sample_var_occupation].groupby(['income']).emotional_engagement_score.mean().sort_values().head(3)
            df_occupation_income = df_occupation_income.to_frame().reset_index()
            #print(df_occupation_income)
            income_list = list(df_occupation_income['income'])
            #print(income_list)
            for i in range(len(income_list)):
                sample_var_income = income_list[i]
                print(sample_var_income)
                vars()[sample_var_income] = vars()[sample_var_occupation].loc[vars()[sample_var_occupation]['income']==income_list[i]]
                vars()[sample_var_income] = vars()[sample_var_income][column_list]
                df_income_age = vars()[sample_var_income].groupby(['age']).emotional_engagement_score.mean().sort_values().head(3)
                df_income_age = df_income_age.to_frame().reset_index()
                #print(df_occupation_income)
                age_list = list(df_income_age['age'])
                print(age_list)
                
                for i in range(len(age_list)):
                    sample_var_age = age_list[i]
                    print(sample_var_age)
                    vars()[sample_var_age] = vars()[sample_var_income].loc[vars()[sample_var_income]['age']==age_list[i]]
                    vars()[sample_var_age] = vars()[sample_var_age][column_list]
                    df_age_gender = vars()[sample_var_age].groupby(['gender']).emotional_engagement_score.mean().sort_values().head(3)
                    df_age_gender = df_age_gender.to_frame().reset_index()
                    #print(df_occupation_income)
                    gender_list = list(df_age_gender['gender'])
                    df_gender = df_gender.append(df_age_gender, ignore_index = False)
                    df_gender = df_gender.append(['new dataframe'], ignore_index = False)
                print(df_gender)
df_gender.rename(columns={'gender':'name'}, inplace = True)

Prefer not to answer
Prefer not to answer
['45-54 years']
45-54 years
               0  emotional_engagement_score gender
0            NaN                      -0.819   Male
0  new dataframe                         NaN    NaN
Paid employment, part time or full time
$70,000 to $89,999
['35-44 years', '25-34 years', '45-54 years']
35-44 years
25-34 years
45-54 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
$30,000 to $49,999
['45-54 years', '55-64 years']
45-54 years
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
$90,000 to $109,999
['18-24 years', '55-64 years', '25-34 years']
18-24 years
55-64 years
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
Retired
$20,000 to $29,999
['65-74 years', '55-64 years']
65-74 years
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
$90,000 to $109,999
['55-64 years']
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
$30,000 to $49,999
['65-74 years']
65-74 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
Paid employment, part time or full time
$150,000 or more
['35-44 years', '55-64 years', '45-54 years']
35-44 years
55-64 years
45-54 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
$110,000 to $149,999
['35-44 years', '18-24 years', '25-34 years']
35-44 years
18-24 years
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
$30,000 to $49,999
['55-64 years', '18-24 years', '35-44 years']
55-64 years
18-24 years
35-44 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN

Other
$10,000 to $19,999
['45-54 years']
45-54 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
$30,000 to $49,999
['45-54 years']
45-54 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
Retired
$150,000 or more
['65-74 years']
65-74 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
$110,000 to $149,999
['65-74 years']
65-74 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
$30,000 to $49,999
['55-64 years', '65-74 years']
55-64 years

65-74 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
Looking for work
Under $10,000
['25-34 years', '55-64 years', '45-54 years']
25-34 years
55-64 years
45-54 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
$50,000 to $69,999
['55-64 years']
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
$20,000 to $29,999
['25-34 years']
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male

0  new dataframe                         NaN     NaN
Student, full or part time
Under $10,000
['18-24 years']
18-24 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
$150,000 or more
['18-24 years']
18-24 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
$30,000 to $49,999
['18-24 years']
18-24 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
Other
$50,000 to $69,999
['55-64 years']
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
$10,000 to $19,999
['35-44 years']
35-44 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female

0  new dataframe                         NaN     NaN
$110,000 to $149,999
['55-64 years']
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
Paid employment, part time or full time
$30,000 to $49,999
['18-24 years', '35-44 years', '25-34 years']
18-24 years
35-44 years
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
Under $10,000
['25-34 years']
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
$110,000 to $149,999

['25-34 years', '55-64 years', '35-44 years']
25-34 years
55-64 years
35-44 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
Homemaker
$20,000 to $29,999
['55-64 years']
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
Prefer not to answer
['35-44 years', '25-34 years']
35-44 years
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
Retired
$10,000 to $19,999

['65-74 years']
65-74 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
$50,000 to $69,999
['55-64 years', '65-74 years']
55-64 years
65-74 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
$70,000 to $89,999
['65-74 years', '55-64 years']
65-74 years
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
Paid employment, part time or full time
$150,000 or more
['55-64 years']
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male

0  new dataframe                         NaN     NaN
Prefer not to answer
['18-24 years', '45-54 years']
18-24 years
45-54 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
$110,000 to $149,999
['45-54 years', '25-34 years', '55-64 years']
45-54 years
25-34 years
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
Other
$30,000 to $49,999
['55-64 years']
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN

0  new dataframe                         NaN     NaN
$90,000 to $109,999
['25-34 years']
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
$50,000 to $69,999
['35-44 years', '45-54 years']
35-44 years
45-54 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
Student, full or part time
$110,000 to $149,999
['18-24 years']
18-24 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female

0  new dataframe                         NaN     NaN
$30,000 to $49,999
['18-24 years']
18-24 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
Prefer not to answer
$30,000 to $49,999
['25-34 years']
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
$10,000 to $19,999
['45-54 years']
45-54 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN

               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
$10,000 to $19,999
['25-34 years']
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
Retired
Under $10,000
['55-64 years']
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female

Student, full or part time
$30,000 to $49,999
['45-54 years']
45-54 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.067    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.737  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.454    Male
0  new dataframe                         NaN     NaN
Prefer not to answer
['25-34 years']
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.067    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.737  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.454    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.573  Female
0  new dataframe                         NaN     NaN
Under $10,000
['25-34 years']
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male

0  new dataframe                         NaN     NaN
Paid employment, part time or full time
Prefer not to answer
['35-44 years', '55-64 years']
35-44 years
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.067    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.737  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.454    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.573  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.368    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.561  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.227  Female
0  new dataframe                         NaN     NaN
$150,000 or more
['55-64 years', '35-44 years', '45-54 years']
55-64 years
35-44 years
45-54 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.067    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.737  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.454    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.573  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.368    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.561  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.227  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.485    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.336  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.897    Male
0  new dataframe                         NaN     NaN
$50,000 to $69,999
['18-24 years', '35-44 years']
18-24 years
35-44 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN

0  new dataframe                         NaN     NaN
Other
$30,000 to $49,999
['25-34 years']
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.067    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.737  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.454    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.573  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.368    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.561  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.227  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.485    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.336  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.897    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.148  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.282  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -2.521    Male
0  new dataframe                         NaN     NaN
$20,000 to $29,999
['45-54 years']
45-54 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.067    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.737  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.454    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.573  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.368    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.561  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.227  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.485    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.336  Female

               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.067    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.737  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.454    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.573  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.368    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.561  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.227  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.485    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.336  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.897    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.148  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.282  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -2.521    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.592    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.748  Female
1            NaN                      -0.801    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
$50,000 to $69,999
['55-64 years', '45-54 years', '65-74 years']
55-64 years
45-54 years
65-74 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.067    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.737  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.454    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.573  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.368    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN

               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.067    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.737  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.454    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.573  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.368    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.561  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.227  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.485    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.336  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.897    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.148  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.282  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -2.521    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.592    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.748  Female
1            NaN                      -0.801    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.530    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.018  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.076    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.592    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.595    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.219    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
Prefer not to answer
Prefer not to answer
['25-34 years']
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.067    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.737  Female

0  new dataframe                         NaN     NaN
Looking for work
$50,000 to $69,999
['25-34 years']
25-34 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.349  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.486  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.171  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.575    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.730  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.067    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.737  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.454    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.573  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.368    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.561  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.227  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.485    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.336  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.897    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.148  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.282  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -2.521    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.592    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.748  Female
1            NaN                      -0.801    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.530    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.018  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.076    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.592    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.595    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.219    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.530  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.555    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.419    Male
1            NaN                      -0.897  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.971    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.611    Male
0  new dataframe                         NaN     NaN
0            NaN                      -2.631    Male
0  new dataframe                         NaN     NaN
$150,000 or more
['55-64 years']
55-64 years
               0  emotional_engagement_score  gender
0            NaN                      -0.819    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.663    Male
1            NaN                      -1.156  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.393  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.159    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.140  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.755  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.033  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.702    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.770  Female
1            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.924    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
1            NaN                      -0.901    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.296  Female
1            NaN                      -1.028    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.511  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.945  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.154    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.993    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.847  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.933    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.736  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.232    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.482    Male
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.411    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.389    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.333    Male
1            NaN                      -0.917  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.389    Male
1            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.735  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.582    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.036  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.374  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.289    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.057  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.141  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.710  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -2.404  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.709  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.497  Female
1            NaN                      -0.394    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.164  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.500  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.523  Female
1            NaN                      -1.135    Male
0  new dataframe                         NaN     NaN
0            NaN                      -0.311  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.444  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.512    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.506  Female
1            NaN                      -0.730    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.522    Male
1            NaN                      -0.747  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.473    Male
1            NaN                      -0.256  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.000    Male
1            NaN                       0.780  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.213    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.409  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.509  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.639    Male
1            NaN                      -1.085  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.155  Female
0  new dataframe                         NaN     NaN
0            NaN                      -1.719  Female
1            NaN                      -0.510    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.222  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.942  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.630  Female
0  new dataframe                         NaN     NaN
0            NaN                       0.145    Male
0  new dataframe                         NaN     NaN
0            NaN                      -1.385  Female
0  new dataframe                         NaN     NaN
0            NaN                      -0.685    Male
0  new dataframe                         NaN     NaN

In [105]:
iccs_tree = pd.concat([iccs_tree, df_gender], ignore_index=True)
iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))

In [106]:
iccs_tree

          name emotional_engagement_score   id parent_id              0 gender
0          NaN                       ICCS    1       NaN            NaN    NaN
1      Ontario                        NaN    2    -0.453            NaN    NaN
2     Manitoba                        NaN    3    -0.413            NaN    NaN
3         Peel                        NaN    4    -0.392            NaN    NaN
4    In-person                     -0.543    5         2            NaN    NaN
..         ...                        ...  ...       ...            ...    ...
732        NaN                        NaN  733       NaN  new dataframe    NaN
733     Female                     -1.107  734       NaN            NaN    NaN
734        NaN                        NaN  735       NaN  new dataframe    NaN
735       Male                      0.815  736       NaN            NaN    NaN
736        NaN                        NaN  737       NaN  new dataframe    NaN

[737 rows x 6 columns]

In [8]:
df_channel = df_channel.append(df_location_channel, ignore_index = True)
df_channel

     channel  emotional_engagement_score
0  In-person                      -0.543
1  Telephone                      -0.533
2     Online                      -0.250
3     Online                      -0.515
4  Telephone                      -0.397
5  In-person                      -0.329
6  Telephone                      -0.511
7     Online                      -0.352
8  In-person                      -0.313

In [80]:
Ontario

        channel          age                               occupation  gender                income  emotional_engagement_score
0        Online  35-44 years  Paid employment, part time or full time    Male  $110,000 to $149,999                       0.000
1        Online  35-44 years  Paid employment, part time or full time    Male  $110,000 to $149,999                       0.299
2        Online  55-64 years  Paid employment, part time or full time  Female    $30,000 to $49,999                       1.273
3        Online  35-44 years  Paid employment, part time or full time  Female   $90,000 to $109,999                       1.273
4     In-person  55-64 years                                  Retired    Male      $150,000 or more                       1.273
...         ...          ...                                      ...     ...                   ...                         ...
2347  In-person  65-74 years                                  Retired    Male    $50,000 to $69,999                      -0.780
2348  In-person  65-74 years                                  Retired  Female    $70,000 to $89,999                       0.266
2349  Telephone  55-64 years                                    Other  Female    $10,000 to $19,999                      -0.226
2350     Online  55-64 years                                  Retired  Female   $90,000 to $109,999                       0.243
2351  Telephone  45-54 years                                    Other    Male    $10,000 to $19,999                      -0.824

[2352 rows x 6 columns]

In [82]:
Telephone

NameError: name 'Telephone' is not defined

In [65]:
Ontario

        channel          age                               occupation  gender                income  emotional_engagement_score
0        Online  35-44 years  Paid employment, part time or full time    Male  $110,000 to $149,999                       0.000
1        Online  35-44 years  Paid employment, part time or full time    Male  $110,000 to $149,999                       0.299
2        Online  55-64 years  Paid employment, part time or full time  Female    $30,000 to $49,999                       1.273
3        Online  35-44 years  Paid employment, part time or full time  Female   $90,000 to $109,999                       1.273
4     In-person  55-64 years                                  Retired    Male      $150,000 or more                       1.273
...         ...          ...                                      ...     ...                   ...                         ...
2347  In-person  65-74 years                                  Retired    Male    $50,000 to $69,999                      -0.780
2348  In-person  65-74 years                                  Retired  Female    $70,000 to $89,999                       0.266
2349  Telephone  55-64 years                                    Other  Female    $10,000 to $19,999                      -0.226
2350     Online  55-64 years                                  Retired  Female   $90,000 to $109,999                       0.243
2351  Telephone  45-54 years                                    Other    Male    $10,000 to $19,999                      -0.824

[2352 rows x 6 columns]

In [39]:
iccs_tree_province = summary_table.groupby(summary_table['location']).emotional_engagement_score.mean().sort_values().head(3)
iccs_tree_province = iccs_tree_province.to_frame().reset_index()
location_list = list(iccs_tree_province['location'])
iccs_tree = pd.DataFrame(columns={ 'parent_id','id','name', 'emotional_engagement_score'})
iccs_tree.loc[0] = ['ICCS', np.nan,np.nan, np.nan]
num_list = [1,2,3]
for i,j in zip(num_list,location_list):
    iccs_tree.loc[i] = [j,np.nan,"1",np.nan]
for i in range(len(location_list)):
    sample_var = location_list[i]
    #print(sample_var)
    vars()[sample_var] = summary_table.loc[summary_table['location']==location_list[i]]
    vars()[sample_var].dropna(axis=1, how='all', inplace=True)
    vars()[sample_var]= summary_table.groupby(summary_table['channel']).emotional_engagement_score.mean().sort_values().head(3)
    vars()[sample_var] = vars()[sample_var].to_frame().reset_index()
    
    vars()[sample_var].reset_index(inplace=True)
    print(vars()[sample_var])
    
    vars()[sample_var] = vars()[sample_var].drop(vars()[sample_var].columns[[0]], axis=1)
    #print(vars()[sample_var])
    channel_list = list(vars()[sample_var]['channel'])
    #print(channel_list)
    vars()[sample_var] = vars()[sample_var].rename(columns = {'channel':'name'})
    for i in range(len(channel_list)):
        sample_var_channel = channel_list[i]
        print(sample_var_channel)
        vars()[sample_var] = summary_table.loc[summary_table['location']==location_list[i]]
    
    iccs_tree = iccs_tree.append(vars()[sample_var], ignore_index = True)
    iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))

# iccs_tree['parent_id'].iloc[4:7] = '2'
# iccs_tree['parent_id'].iloc[7:10] = '3'
# iccs_tree['parent_id'].iloc[10:13] = '4'

<ipython-input-39-6181f66a0730>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vars()[sample_var].dropna(axis=1, how='all', inplace=True)
<ipython-input-39-6181f66a0730>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vars()[sample_var].dropna(axis=1, how='all', inplace=True)
<ipython-input-39-6181f66a0730>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vars()[sample_var].dropna(axis=1, how='all', inplace=True)

   index    channel  emotional_engagement_score
0      0  Telephone                      -0.277
1      1     Online                      -0.259
2      2  In-person                      -0.244
Telephone
Online
In-person
   index    channel  emotional_engagement_score
0      0  Telephone                      -0.277
1      1     Online                      -0.259
2      2  In-person                      -0.244
Telephone
Online
In-person
   index    channel  emotional_engagement_score
0      0  Telephone                      -0.277
1      1     Online                      -0.259
2      2  In-person                      -0.244
Telephone
Online
In-person

In [35]:
iccs_tree

         name  id parent_id  emotional_engagement_score
0        ICCS   1       NaN                         NaN
1     Ontario   2         1                         NaN
2    Manitoba   3         1                         NaN
3        Peel   4         1                         NaN
4   Telephone   5       NaN                      -0.277
5      Online   6       NaN                      -0.259
6   In-person   7       NaN                      -0.244
7   Telephone   8       NaN                      -0.277
8      Online   9       NaN                      -0.259
9   In-person  10       NaN                      -0.244
10  Telephone  11       NaN                      -0.277
11     Online  12       NaN                      -0.259
12  In-person  13       NaN                      -0.244

In [13]:
iccs_tree_province = summary_table.groupby(summary_table['location']).emotional_engagement_score.mean().sort_values().head(3)

In [ ]:
# connection = pg.connect('postgresql://aidatabases:Aidatabases#@65.1.96.15:5432/pathos_db')
# engine = create_engine('postgresql://aidatabases:Aidatabases#@65.1.96.15:5432/pathos_db')
# push_table_pgres(df, df_name = 'rb_tree_temp2', schema= 'pathos_rb_schema')

# Location

In [5]:
# iccs_tree_province=pd.DataFrame()
# iccs_tree_province=pd.DataFrame(columns={'province_id','name','id'})
# iccs_tree_province.loc[0] = [np.nan,'ICCS',1]
# iccs_tree_province

    id  name province_id
0  NaN  ICCS           1

In [6]:
# df_top_province=pd.DataFrame(summary_table.groupby(summary_table['location']).emotional_engagement_score.mean().sort_values().head(3))
# df_top_province=df_top_province.reset_index()
# df_top_province=df_top_province.rename(columns={'province':'name'})
# df_top_province['id']=df_top_province.index+2
# df_top_province['parent_id']=1

In [7]:
# iccs_tree_province=pd.concat([iccs_tree_province,df_top_province])
# iccs_tree_province

    id  name province_id  location  emotional_engagement_score  parent_id
0  NaN  ICCS           1       NaN                         NaN        NaN
0    2   NaN         NaN   Ontario                      -0.453      1.000
1    3   NaN         NaN  Manitoba                      -0.413      1.000
2    4   NaN         NaN      Peel                      -0.392      1.000

In [64]:
iccs_tree_province

   location  emotional_engagement_score
0   Ontario                      -0.453
1  Manitoba                      -0.413
2      Peel                      -0.392

In [68]:
location_dict = pd.Series(iccs_tree_province.emotional_engagement_score.values,index=iccs_tree_province.location).to_dict()

In [84]:
location_list = list(location_dict.keys())
location_list

['Ontario', 'Manitoba', 'Peel']

In [219]:
iccs_tree_top_province()

Ontario
Manitoba
Peel

<ipython-input-218-1c542406a32d>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vars()[sample_var].dropna(axis=1, how='all', inplace=True)
<ipython-input-218-1c542406a32d>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vars()[sample_var].dropna(axis=1, how='all', inplace=True)
<ipython-input-218-1c542406a32d>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vars()[sample_var].dropna(axis=1, how='all', inplace=True)

In [217]:
iccs_tree = pd.DataFrame(columns={ 'parent_id','id','name', 'driver_score'})
iccs_tree.loc[0] = [np.nan,np.nan, 'ICCS', np.nan]
num_list = [1,2,3]
for i,j in zip(num_list,location_list):
    iccs_tree.loc[i] = [np.nan,np.nan, j,"1"]
for i in range(len(location_list)):
    sample_var = location_list[i]
    print(sample_var)
    vars()[sample_var] = summary_table.loc[summary_table['location']==location_list[i]]
    vars()[sample_var].dropna(axis=1, how='all', inplace=True)
    common_drivers = list(set(drivers_list).intersection(vars()[sample_var].columns))
    vars()[sample_var]= vars()[sample_var][common_drivers].mean().sort_values().head(3)
    vars()[sample_var] = vars()[sample_var].to_frame().reset_index()
    vars()[sample_var].reset_index(inplace=True)
    vars()[sample_var] = vars()[sample_var].drop(vars()[sample_var].columns[[0]], axis=1) 
    vars()[sample_var] = vars()[sample_var].rename(columns = {'index':'name', 0:'driver_score'})
    iccs_tree = iccs_tree.append(vars()[sample_var], ignore_index = True)
    iccs_tree['id'] = list(range(1, iccs_tree.shape[0]+1))
iccs_tree['parent_id'].iloc[4:7] = '2'
iccs_tree['parent_id'].iloc[7:10] = '3'
iccs_tree['parent_id'].iloc[10:13] = '4'

Ontario
Manitoba
Peel

<ipython-input-217-646863c4f903>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vars()[sample_var].dropna(axis=1, how='all', inplace=True)
<ipython-input-217-646863c4f903>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vars()[sample_var].dropna(axis=1, how='all', inplace=True)
<ipython-input-217-646863c4f903>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vars()[sample_var].dropna(axis=1, how='all', inplace=True)
C:\Users\Abhishek\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [213]:
iccs_tree = iccs_tree.astype(str)

In [215]:
iccs_tree

            driver_score  id                                name parent_id
0                    nan   1                                ICCS       nan
1                    nan   2                             Ontario         1
2                    nan   3                            Manitoba         1
3                    nan   4                                Peel         1
4    -0.4840758831909163   5          drivers_waiting_time_score         2
5   -0.12346757450711521   6            drivers_timeliness_score         2
6   -0.11361433440261609   7         drivers_communication_score         2
7   -0.43674101101844737   8          drivers_waiting_time_score         3
8   -0.16634945819945787   9            drivers_timeliness_score         3
9   -0.11717156631269905  10  drivers_channel_satisfaction_score         3
10  -0.36655147347719974  11          drivers_waiting_time_score         4
11   -0.2047239338218802  12            drivers_timeliness_score         4
12  -0.12597768283476934  13            drivers_competence_score         4

## Drivers

In [34]:
common_drivers = list(set(drivers_list).intersection(ontario_table.columns))

In [37]:
ontario_table[common_drivers].mean().sort_values().head(3)

drivers_waiting_time_score    -0.484
drivers_timeliness_score      -0.123
drivers_communication_score   -0.114
dtype: float64

# Ontario

In [17]:
ontario_table = summary_table.loc[summary_table['location']=='Ontario']

In [20]:
ontario_table.dropna(axis=1, how='all', inplace=True)

In [18]:
column_list = ['channel', 'age', 'occupation', 'gender', 'emotional_engagement_score']

In [19]:
ontario_table = ontario_table[drivers_list+ column_list]

## Age

In [22]:
ontario_top_age = ontario_table.groupby(ontario_table['age']).emotional_engagement_score.mean().sort_values().head(3)

In [23]:
ontario_top_age

age
35-44 years   -0.558
18-24 years   -0.550
55-64 years   -0.513
Name: emotional_engagement_score, dtype: float64

## Occupation

In [24]:
ontario_top_occupation = ontario_table.groupby(ontario_table['occupation']).emotional_engagement_score.mean().sort_values().head(3)

In [25]:
ontario_top_occupation

occupation
Prefer not to answer                      -0.581
Student, full or part time                -0.572
Paid employment, part time or full time   -0.559
Name: emotional_engagement_score, dtype: float64

## Channel

In [26]:
ontario_top_channel = ontario_table.groupby(ontario_table['channel']).emotional_engagement_score.mean().sort_values().head(3)

In [27]:
ontario_top_channel

channel
In-person   -0.543
Telephone   -0.533
Online      -0.250
Name: emotional_engagement_score, dtype: float64

In [29]:
ontario_table

      drivers_positivity_score  drivers_security_score  drivers_convenience_score  drivers_care_score  drivers_timeliness_score  drivers_respect_score  drivers_knowledge_score  drivers_fairness_score  drivers_channel_satisfaction_score  drivers_outcome_score  drivers_communication_score  drivers_ease_of_access_score  drivers_competence_score  drivers_waiting_time_score  drivers_trust_score  drivers_innovative_score    channel          age                               occupation  gender  emotional_engagement_score
271                      0.000                   0.000                      0.000               0.000                     0.000                  0.000                   -0.000                   0.000                               0.000                  0.000                        0.000                         0.000                     0.000                      -2.407                0.000                     0.000  In-person  65-74 years                                  Retired    Male                      -1.100
272                      0.100                   0.001                      0.045               0.024                     2.424                  0.004                    0.000                   0.000                               0.001                  0.050                        0.001                         0.001                     0.000                       0.011                0.000                     0.000     Online  55-64 years  Paid employment, part time or full time    Male                       2.404
273                      0.100                   0.001                      0.045               0.024                     2.424                  0.004                    0.000                   0.000                               0.001                  0.050                        0.001                         0.001                     0.000                       0.011                0.000                     0.000     Online  55-64 years                                Homemaker  Female                       2.404
298                      0.000                   0.000                      0.000               0.000                     0.000                  0.000                   -0.000                   0.000                               0.000                  0.000                        0.000                         0.000                     0.000                      -2.557                0.000                     0.000  Telephone  65-74 years                                  Retired    Male                      -1.377
306                     -0.092                  -0.000                     -0.242              -0.095                    -0.084                  0.000                   -0.001                   0.000                              -0.044                 -0.111                       -0.016                        -0.030                     0.000                      -0.003                0.000                    -0.000     Online  45-54 years  Paid employment, part time or full time  Female                      -0.036
307                     -0.092                  -0.000                     -0.242              -0.095                    -0.084                  0.000                   -0.001                   0.000                              -0.044                 -0.111                       -0.016                        -0.030                     0.000                      -0.003                0.000                    -0.000  Telephone  18-24 years               Student, full or part time    Male                      -0.036
308                     -0.092                  -0.000                     -0.242              -0.095                    -0.084                  0.000                   -0.001                   0.000                              -0.044                 -0.111                       -0.016                        -0.030                     0.000                      -0.003                0.000                    -0.000     Online  55-64 years                         Looking for work  Female                      -0.036
316                     -0.003                   0.000                     -0.001              -0.001                    -0.001                  0.000                   -0.014                   0.000                               0.000                  0.000                       -0.005                        -0.002                     0.000                      -2.513                0.000                     0.000  In-person  35-44 years               Student, full or part time    Male                      -1.386
317                     -0.003                   0.000                     -0.001              -0.001                    -0.001                  0.000                   -0.014                   0.000                               0.000                  0.000                       -0.005                        -0.002                     0.000                      -2.513                0.000                     0.000     Online  18-24 years               Student, full or part time  Female                      -1.386
328                     -0.003                   0.000                     -0.003              -0.000                    -0.017                  0.000                   -0.001                   0.000                              -0.000                  0.000                       -0.001                        -0.771                    -0.843                      -0.353                0.000                     0.000  Telephone  45-54 years  Paid employment, part time or full time  Female                      -0.810
347                     -0.017                   0.000                     -0.028              -0.208                    -0.745                 -0.000                   -0.000                  -0.001                              -0.001                 -0.003                       -0.085                        -0.000                     0.000                      -1.669                0.000                     0.000     Online  55-64 years                                  Retired    Male                      -1.526
348                     -0.017                   0.000                     -0.028              -0.208                    -0.745                 -0.000                   -0.000                  -0.001                              -0.001                 -0.003                       -0.085                        -0.000                     0.000                      -1.669                0.000                     0.000  Telephone  18-24 years               Student, full or part time  Female                      -1.526
349                     -0.017                   0.000                     -0.028              -0.208                    -0.745                 -0.000                   -0.000                  -0.001                              -0.001                 -0.003                       -0.085                        -0.000                     0.000                      -1.669                0.000                     0.000  In-person  65-74 years                                  Retired    Male                      -1.526
356                     -0.183                  -0.001                     -0.425              -0.200                    -0.701                 -0.000                   -0.001                   0.000                              -0.198                 -0.187                       -0.666                        -0.022                     0.000                      -0.029                0.000                    -0.008  In-person  65-74 years                                  Retired    Male                      -1.515
390                      0.191                   0.000                      0.006               0.047                     0.002                  0.000                    0.000                   0.000                               0.000                  1.517                        0.000                         0.000                     0.000                       0.000                0.000                     0.000  In-person  55-64 years                                Homemaker  Female                       1.065
394                     -0.000                   0.000                      0.000              -0.000                     0.000                  0.000                   -0.066                   0.000                               0.000                  0.000                       -0.129                        -0.001                     0.000                      -2.431                0.000                     0.000  In-person  55-64 years                                  Retired  Female                      -1.385
415                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN  In-person  35-44 years  Paid employment, part time or full time    Male                       0.000
430                      0.000                   0.000                      0.000               0.000                     0.000                  0.000                   -0.001                   0.000                               0.000                  0.000                        0.000                         0.000                     0.000                      -2.730                0.000                     0.000  Telephone  55-64 years  Paid employment, part time or full time    Male                      -1.530
463                     -0.002                   0.000                     -0.014              -0.000                    -0.000                  0.000                   -0.001                   0.000                              -0.003                 -0.000                        0.000                        -1.768                     0.000                      -0.000                0.000                     0.000  In-person  55-64 years                                    Other    Male                      -0.683
473                     -0.016                  -0.000                     -0.021              -1.678                    -0.003                 -0.000                   -0.020                   0.000                              -0.000                 -0.003                       -0.016                         0.000                     0.000                      -0.855                0.000                     0.000  Telephone  55-64 years                                  Retired    Male                      -1.333
482                     -0.003                   0.000                     -0.005              -0.006                    -0.006                  0.000                   -0.000                   0.000                              -0.002                 -0.008                       -0.763                        -0.000                     0.000                       0.000                0.000                     0.000  In-person  45-54 years  Paid employment, part time or full time    Male                      -0.112
483                     -0.003                   0.000                     -0.005              -0.006                    -0.006                  0.000                   -0.000                   0.000                              -0.002                 -0.008                       -0.763                        -0.000                     0.000                       0.000                0.000                     0.000  In-person  45-54 years                         Looking for work  Female                      -0.112
513                     -0.001                  -0.000                     -0.004              -0.004                     0.000                  0.000                   -0.699                   0.000                              -0.002                 -0.016                       -1.201                         0.000                     0.000                       0.000                0.000                     0.000  In-person  65-74 years  Paid employment, part time or full time  Female                      -0.736
540                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN  In-person  55-64 years  Paid employment, part time or full time    Male                       0.000
551                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN  Telephone  45-54 years  Paid employment, part time or full time    Male                       0.000
569                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  65-74 years                                  Retired    Male                       0.000
576                      0.172                   0.000                      0.168               0.254                     2.316                  0.017                    0.002                   0.000                               0.008                  0.598                        0.045                         0.002                     0.000                       0.002                0.000                     0.000     Online  65-74 years                                  Retired    Male                       4.393
593                     -0.005                   0.000                     -0.008              -0.052                    -0.037                 -0.001                   -0.003                   0.000                              -0.003                 -0.061                       -1.842                         0.000                     0.000                      -0.000                0.000                     0.000  In-person  45-54 years                     Prefer not to answer    Male                      -0.819
596                     -0.017                   0.000                     -0.013              -0.020                    -0.000                  0.000                    0.000                   0.000                              -0.000                 -0.095                       -0.001                        -0.000                    -0.001                       0.000                0.000                     0.000  Telephone  55-64 years  Paid employment, part time or full time    Male                       0.001
597                     -0.017                   0.000                     -0.013              -0.020                    -0.000                  0.000                    0.000                   0.000                              -0.000                 -0.095                       -0.001                        -0.000                    -0.001                       0.000                0.000                     0.000  Telephone  65-74 years                                  Retired    Male                       0.001
598                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  25-34 years  Paid employment, part time or full time  Female                       0.000
599                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  45-54 years                                    Other    Male                       0.000
607                     -0.037                   0.000                     -0.026              -0.064                    -0.009                 -0.000                   -0.000                   0.000                              -0.002                 -0.232                       -0.012                        -0.000                    -0.000                       0.000                0.000                     0.000  In-person  65-74 years                                  Retired    Male                      -0.002
625                      0.195                   0.000                      0.143               0.176                     0.021                  0.000                    0.000                   0.000                               0.009                  0.655                        0.057                         0.000                     0.000                       0.000                0.000                     0.000  In-person  65-74 years  Paid employment, part time or full time    Male                       0.472
648                      0.061                   0.000                      0.023               0.102                     0.008                  0.000                    0.000                   0.000                               0.000                  0.233                        0.001                         0.000                     0.000                       0.000                0.000                     0.000  In-person  45-54 years  Paid employment, part time or full time  Female                       0.021
649                      0.061                   0.000                      0.023               0.102                     0.008                  0.000                    0.000                   0.000                               0.000                  0.233                        0.001                         0.000                     0.000                       0.000                0.000                     0.000  In-person  65-74 years                                  Retired  Female                       0.021
659                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  45-54 years                                    Other  Female                       0.000

# Manitoba

In [15]:
manitoba_table = summary_table.loc[summary_table['location']=='Manitoba']

In [16]:
manitoba_table

      pathos_summary_id review_id client_transaction_id client_transaction_date message_desc  q5a_1  q5a_2  q5a_3 q5a_4 q5a_5  q5a_6  q5a_7 q5a_8  q5a_9  q5a_10 q5b_1 q5b_2  q5b_3 q5b_4  q5b_5  q5b_6  q5b_7 q5b_8 q5b_9  q6_1  q6_2  q6_3  q6_4  q6_5  q6_6  q6_7  q6_8  q6_9  q6_10  q6_11  q8a_1 q8a_2 q8a_3  q8a_4  q8a_5 q8a_6  q8a_7  q8a_8 q8a_9 q8b_1  q8b_2 q8b_3  q8b_4  q8b_5  q8b_6 q8c_1 q8c_2  q8c_3  q8c_4 q8c_5  q8c_6  q8d_1 q8d_2 q8d_3  q8d_4 q8d_5  q8e_1  q8e_2  q8e_3 q8e_4 q8f_1  q8f_2 q8f_3 q8f_4  q8f_5 q8f_6  q8f_7  q8f_8  q8g_1 q8g_2 q8g_3  q8g_4 q8g_5 q8g_6  q8g_7  q8g_8  q8g_9  q5_01  q5_02  q5_03 q5_04 q5_05  q5_06  q5_07 q5_08  q5_09  q5_10 q5_11 q5_12  q5_13 q5_14  q5_15  q5_16  q5_17 q5_18 q6_01  q6_02  q6_03 q6_04  q6_05  q6_06 q6_07 q6_08  q6_09  q8a_01  q8a_02  q8a_03 q8a_04 q8a_05  q8a_06  q8b_01 q8b_02  q8b_03  q8b_04 q8b_05 q8b_06  q8c_01 q8c_02  q8c_03  q8c_04  q8c_05 q8d_01 q8d_02  q8d_03  q8d_04 q8d_05  q8e_01  q8e_02 q8e_03 q8e_04  q8f_01 q8f_02  q8f_03  \
266             264.000      None                  None                    None         None  4.000  3.000  4.000  None  None  3.000  3.000  None  2.000   6.000  None  None  6.000  None  6.000  3.000  3.000  None  None 4.000 6.000  None 6.000 6.000  None  None 6.000  None  6.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  None  None  6.000  None  4.000  6.000  3.000  None  None  6.000  None  None  6.000  6.000  6.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
267             265.000      None                  None                    None         None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN     NaN  None  None    NaN  None    NaN    NaN    NaN  None  None   NaN   NaN  None   NaN   NaN  None  None   NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN  None  None    NaN    NaN    NaN  4.000  4.000  4.000  None  None  4.000    NaN  None  3.000    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN  3.000  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
309             307.000      None                  None                    None         None  4.000  4.000  4.000  None  None  3.000  4.000  None  4.000   5.000  None  None  5.000  None  4.000  6.000  6.000  None  None 3.000 6.000  None 6.000 6.000  None  None 6.000  None  4.000  4.000  2.000  None  None  6.000  6.000  None  3.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  3.000  None  2.000  3.000  None  None  6.000  None  3.000  3.000  3.000  None  None  6.000  None  None  6.000  None  4.000  4.000  4.000  None  None  6.000  None  None  6.000  4.000  4.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
364             405.000      None                  None                    None         None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN     NaN  None  None    NaN  None    NaN    NaN    NaN  None  None   NaN   NaN  None   NaN   NaN  None  None   NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN  None  None    NaN    NaN    NaN  4.000  4.000  4.000  None  None  4.000  2.000  None  2.000    NaN  None  None    NaN  None  3.000  5.000  5.000  None  None    NaN    NaN  None    NaN    NaN  None  None  3.000     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
365             362.000      None                  None                    None         None  4.000  1.000  3.000  None  None  4.000  5.000  None  4.000   3.000  None  None  3.000  None  4.000  4.000  3.000  None  None 3.000 3.000  None 6.000 4.000  None  None 4.000  None  4.000  4.000  6.000  None  None  6.000  6.000  None  5.000  6.000  None  None  6.000  None  3.000  6.000  6.000  None  None  6.000  3.000  None  3.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  None  None  6.000  None  3.000  6.000  3.000  None  None  6.000  None  None  6.000  5.000  5.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
374             371.000      None                  None                    None         None  4.000  3.000  4.000  None  None  4.000  4.000  None  4.000   5.000  None  None  5.000  None  4.000  6.000  6.000  None  None 6.000 6.000  None 6.000 6.000  None  None 4.000  None  6.000  4.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  None  None  6.000  None  5.000  5.000  6.000  None  None  6.000  None  None  6.000  5.000  5.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
375             372.000      None                  None                    None         None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN     NaN  None  None    NaN  None    NaN    NaN    NaN  None  None   NaN   NaN  None   NaN   NaN  None  None   NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN  None  None    NaN    NaN    NaN    NaN    NaN    NaN  None  None    NaN  3.000  None    NaN    NaN  None  None  3.000  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None   5.000
386             406.000      None                  None                    None         None  6.000  4.000  4.000  None  None  6.000  4.000  None  2.000   6.000  None  None  6.000  None  6.000  6.000  6.000  None  None 6.000 6.000  None 6.000 6.000  None  None 6.000  None  6.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  None  None  6.000  None  3.000  6.000  6.000  None  None  6.000  None  None  6.000  3.000  2.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
389             385.000      None                  None                    None         None  4.000  4.000  4.000  None  None  4.000  3.000  None  4.000   5.000  None  None  5.000  None  4.000  4.000  5.000  None  None 4.000 6.000  None 6.000 4.000  None  None 4.000  None  6.000  4.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  None  None  6.000  None  4.000  6.000  4.000  None  None  4.000  None  None  6.000  6.000  4.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
408             404.000      None                  None                    None         None  3.000  4.000  5.000  None  None  4.000  4.000  None  3.000   5.000  None  None  5.000  None  5.000  6.000  5.000  None  None 6.000 6.000  None 6.000 6.000  None  None 5.000  None  4.000  5.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  2.000  6.000  None  None  6.000  6.000  None  6.000  5.000  None  None  3.000  None  6.000  6.000  6.000  None  None  6.000  None  None  6.000  None  4.000  4.000  6.000  None  None  6.000  None  None  6.000  6.000  1.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
457             457.000      None                  None                    None         None  5.000  3.000  4.000  None  None  6.000  4.000  None  3.000   5.000  None  None  5.000  None  6.000  6.000  6.000  None  None 6.000 6.000  None 6.000 6.000  None  None 5.000  None  6.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  3.000  6.000  6.000  None  None  6.000  None  None  6.000  None  5.000  6.000  3.000  None  None  6.000  None  None  6.000  6.000  5.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
464             464.000      None                  None                    None         None  1.000  1.000  1.000  None  None  1.000  3.000  None  1.000   5.000  None  None  5.000  None  5.000  1.000  4.000  None  None 1.000 6.000  None 6.000 6.000  None  None 5.000  None  4.000  5.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  1.000  None  6.000  1.000  None  None  2.000  None  3.000  6.000  6.000  None  None  5.000  None  None  6.000  None  4.000  4.000  1.000  None  None  6.000  None  None  1.000  3.000  6.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
471             471.000      None                  None                    None         None  4.000  5.000  5.000  None  None  4.000  3.000  None  4.000   6.000  None  None  6.000  None  3.000  6.000  6.000  None  None 6.000 2.000  None 6.000 6.000  None  None 3.000  None  6.000  4.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  3.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  None  None  6.000  None  3.000  6.000  3.000  None  None  3.000  None  None  6.000  6.000  6.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
472             472.000      None                  None                    None         None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN     NaN  None  None    NaN  None    NaN    NaN    NaN  None  None   NaN   NaN  None   NaN   NaN  None  None   NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN  None  None    NaN    NaN    NaN  5.000  5.000    NaN  None  None  5.000  5.000  None  4.000    NaN  None  None  5.000  None    NaN  5.000    NaN  None  None    NaN  5.000  None    NaN    NaN  None  None  5.000     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
480             480.000      None                  None                    None         None  5.000  4.000  4.000  None  None  3.000  3.000  None  4.000   2.000  None  None  2.000  None  4.000  4.000  4.000  None  None 4.000 4.000  None 4.000 4.000  None  None 4.000  None  3.000  5.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  None  None  4.000  None  4.000  4.000  4.000  None  None  4.000  None  None  6.000  6.000  6.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
481             481.000      None                  None                    None         None  4.000  4.000  4.000  None  None  3.000  2.000  None  4.000   4.000  None  None  4.000  None  6.000  6.000  6.000  None  None 6.000 6.000  None 6.000 6.000  None  None 3.000  None  3.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  3.000  6.000  None  None  6.000  None  None  6.000  None  4.000  3.000  3.000  None  None  3.000  None  None  6.000  6.000  6.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
494             493.000      None                  None                    None         None  5.000  5.000  5.000  None  None  5.000  5.000  None  5.000   6.000  None  None  6.000  None  4.000  6.000  6.000  None  None 6.000 6.000  None 6.000 5.000  None  None 5.000  None  6.000  5.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  4.000  None  4.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  None  None  6.000  None  5.000  6.000  6.000  None  None  6.000  None  None  6.000  6.000  6.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN
495             494.000      None                  None                    None         None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN     NaN  None  None    NaN  None    NaN    NaN    NaN  None  None   NaN   NaN  None   NaN   NaN  None  None   NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN  None  None    NaN    NaN    NaN  5.000    NaN  4.000  None  None    NaN    NaN  None  5.000  5.000  None  None  5.000  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None  5.000     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN   5.000   None     NaN     NaN   None   None     NaN   None     NaN
523             522.000      None                  None                    None         None  3.000  5.000  5.000  None  None  3.000  5.000  None  3.000   5.000  None  None  5.000  None  4.000  6.000  3.000  None  None 6.000 6.000  None 2.000 3.000  None  None 3.000  None  6.000  3.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  6.000  None  6.000  6.000  None  None  6.000  None  6.000  6.000  6.000  None  None  6.000  None  None  6.000  None  5.000  4.000  6.000  None  None  6.000  None  None  6.000  6.000  6.000    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN  None    NaN    NaN    NaN  None  None    NaN    NaN  None    NaN    NaN  None  None    NaN     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN     NaN     NaN   None   None     NaN     NaN   None     NaN     NaN   None   None     NaN   None     NaN

In [17]:
column_list = ['channel', 'age', 'occupation', 'gender', 'emotional_engagement_score']

In [18]:
manitoba_table = manitoba_table[drivers_list+ column_list]

In [20]:
manitoba_table.dropna(axis=1, how='all', inplace=True)

<ipython-input-20-3194c3f431b0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  manitoba_table.dropna(axis=1, how='all', inplace=True)

In [21]:
manitoba_table

      drivers_positivity_score  drivers_security_score  drivers_convenience_score  drivers_care_score  drivers_timeliness_score  drivers_respect_score  drivers_knowledge_score  drivers_fairness_score  drivers_channel_satisfaction_score  drivers_outcome_score  drivers_communication_score  drivers_ease_of_access_score  drivers_competence_score  drivers_waiting_time_score  drivers_trust_score  drivers_innovative_score    channel          age                               occupation  gender  emotional_engagement_score
266                     -0.006                   0.000                     -0.017              -0.001                    -0.001                  0.000                   -0.008                   0.000                              -0.007                 -0.000                       -0.000                        -1.868                     0.000                      -0.005                0.000                     0.000     Online  55-64 years                                  Retired    Male                      -0.730
267                     -0.006                   0.000                     -0.017              -0.001                    -0.001                  0.000                   -0.008                   0.000                              -0.007                 -0.000                       -0.000                        -1.868                     0.000                      -0.005                0.000                     0.000  In-person  25-34 years                                    Other  Female                      -0.730
309                     -0.018                   0.000                     -0.072              -0.002                    -0.015                  0.000                   -0.017                   0.000                              -1.712                 -0.002                       -0.004                        -0.120                     0.000                      -0.005                0.000                     0.000     Online  45-54 years  Paid employment, part time or full time    Male                      -0.794
364                     -0.006                   0.000                     -0.031              -0.051                    -0.000                  0.000                    0.000                  -2.227                               0.000                 -0.004                       -0.001                         0.000                     0.000                       0.000                0.000                     0.000  In-person  55-64 years                                  Retired    Male                      -1.039
365                     -0.190                  -0.002                     -0.141              -0.855                    -1.173                 -0.013                   -0.012                   0.000                              -0.010                 -0.299                       -0.039                        -0.001                     0.000                      -0.046                0.000                     0.000     Online  35-44 years  Paid employment, part time or full time  Female                      -1.709
374                      0.000                   0.000                      0.000               0.000                     0.000                  0.000                   -0.000                   0.000                               0.000                  0.000                        0.000                         0.000                     0.000                      -2.707                0.000                     0.000     Online  25-34 years  Paid employment, part time or full time  Female                      -1.500
375                      0.000                   0.000                      0.000               0.000                     0.000                  0.000                   -0.000                   0.000                               0.000                  0.000                        0.000                         0.000                     0.000                      -2.707                0.000                     0.000  In-person  65-74 years                                  Retired  Female                      -1.500
386                     -0.001                   0.000                      0.000              -0.018                     0.000                 -2.673                    0.000                   0.000                               0.000                 -0.024                        0.000                         0.000                     0.000                       0.000                0.000                     0.000     Online  65-74 years                                  Retired    Male                      -1.522
389                     -0.116                   0.000                     -0.093              -0.692                    -0.003                  0.000                   -0.000                   0.000                              -0.001                 -0.313                       -0.002                         0.000                    -0.003                       0.000                0.000                     0.000  Telephone  65-74 years                                  Retired    Male                      -0.288
408                     -0.006                   0.000                     -0.031              -0.051                    -0.000                  0.000                    0.000                  -2.227                               0.000                 -0.004                       -0.001                         0.000                     0.000                       0.000                0.000                     0.000  Telephone  35-44 years  Paid employment, part time or full time  Female                      -1.039
457                      0.000                   0.000                      0.000              -0.002                     0.000                  0.000                   -1.590                   0.000                               0.000                 -0.004                       -0.000                         0.000                     0.000                       0.000                0.000                     0.000  Telephone  45-54 years  Paid employment, part time or full time  Female                      -0.509
464                     -0.029                   0.000                     -0.077              -0.279                    -0.023                 -0.000                   -0.028                   0.000                              -0.000                 -0.009                       -0.001                        -0.011                    -1.578                      -0.001                0.000                     0.000  In-person  45-54 years                                Homemaker    Male                      -0.854
471                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  55-64 years                                  Retired    Male                       0.000
472                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  55-64 years                                  Retired    Male                       0.000
480                     -0.241                  -0.001                     -0.569              -0.321                    -0.218                  0.000                   -0.010                   0.000                              -0.156                 -0.447                       -0.030                        -0.127                     0.000                      -0.006                0.000                    -0.000  Telephone  55-64 years  Paid employment, part time or full time    Male                      -0.901
481                     -0.006                   0.000                     -0.004              -0.047                    -0.026                 -0.000                   -0.001                   0.000                              -0.000                 -0.004                       -0.019                         0.000                    -1.045                      -0.003                0.000                     0.000     Online  35-44 years  Paid employment, part time or full time  Female                      -0.263
494                     -0.002                  -0.000                     -0.000              -0.001                    -0.001                  0.000                   -0.002                   0.000                               0.000                  0.000                       -0.012                         0.000                     0.000                      -2.595                0.000                     0.000  Telephone  55-64 years  Paid employment, part time or full time    Male                      -1.434
495                     -0.002                  -0.000                     -0.000              -0.001                    -0.001                  0.000                   -0.002                   0.000                               0.000                  0.000                       -0.012                         0.000                     0.000                      -2.595                0.000                     0.000  Telephone  25-34 years                                Homemaker  Female                      -1.434
523                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  65-74 years                                  Retired    Male                       0.000
528                     -0.002                  -0.000                     -0.001              -0.002                    -0.002                 -0.003                   -0.011                   0.000                               0.000                  0.000                       -0.020                        -0.000                     0.000                      -2.601                0.000                     0.000     Online  65-74 years                                  Retired    Male                      -1.473
529                     -0.002                  -0.000                     -0.001              -0.002                    -0.002                 -0.003                   -0.011                   0.000                               0.000                  0.000                       -0.020                        -0.000                     0.000                      -2.601                0.000                     0.000  In-person  55-64 years                                    Other    Male                      -1.473
538                      0.107                   0.001                      0.134               0.078                     0.020                  0.000                    0.000                   0.000                               0.139                  0.297                        0.006                         0.004                     0.000                       0.000                0.000                     0.000  Telephone  45-54 years                                    Other    Male                       0.145
556                      0.420                   0.000                      1.063               0.265                     0.061                  0.000                    0.000                   0.000                               0.168                  0.677                        0.004                         0.061                     0.000                       0.000                0.000                     0.000  In-person  35-44 years  Paid employment, part time or full time    Male                       2.566
557                      0.420                   0.000                      1.063               0.265                     0.061                  0.000                    0.000                   0.000                               0.168                  0.677                        0.004                         0.061                     0.000                       0.000                0.000                     0.000  Telephone  55-64 years                         Looking for work  Female                       2.566
559                      0.000                   0.000                      0.000               0.000                     0.000                  0.000                    0.093                   0.000                               0.000                  0.000                        0.000                         0.001                     0.000                       1.195                0.000                     0.000  In-person  45-54 years  Paid employment, part time or full time  Female                       0.505
568                      0.100                   0.000                      0.079               0.150                     0.060                  0.000                    0.000                   0.000                               0.022                  0.398                        0.010                         0.000                     0.000                       0.000                0.000                     0.000  Telephone  55-64 years  Paid employment, part time or full time  Female                       0.140
570                      0.000                   0.000                      0.000               0.000                     0.000                 -0.000                   -0.376                   0.000                               0.000                  0.000                       -0.000                        -0.000                     0.000                      -2.298                0.000                     0.000     Online  55-64 years                                  Retired  Female                      -1.506
571                      0.000                   0.000                      0.000               0.000                     0.000                 -0.000                   -0.376                   0.000                               0.000                  0.000                       -0.000                        -0.000                     0.000                      -2.298                0.000                     0.000     Online  55-64 years                                Homemaker  Female                      -1.506
578                      0.000                   0.000                      0.000               0.000                     0.000                  0.000                    0.000                   0.000                               0.000                  0.000                        0.000                         0.000                     0.000                      -2.306                0.000                     0.000  Telephone  55-64 years  Paid employment, part time or full time    Male                      -0.992
585                      0.273                   0.000                      0.185               0.128                     0.005                  0.000                    0.000                   0.000                               0.011                  0.962                        0.001                         0.001                     0.000                       0.000                0.000                     0.000     Online  55-64 years                                  Retired  Female                       0.780
601                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN  In-person  65-74 years                                  Retired    Male                       0.000
602                     -0.001                   0.000                     -0.003              -0.034                    -0.000                 -0.386                   -0.039                   0.000                               0.000                 -0.011                       -0.019                         0.000                    -0.001                      -0.000                0.000                     0.000     Online  45-54 years  Paid employment, part time or full time  Female                      -0.007
603                     -0.001                   0.000                     -0.003              -0.034                    -0.000                 -0.386                   -0.039                   0.000                               0.000                 -0.011                       -0.019                         0.000                    -0.001                      -0.000                0.000                     0.000  Telephone  45-54 years                         Looking for work  Female                      -0.007
623                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN  Telephone  65-74 years                                  Retired    Male                       0.000
641                     -0.000                   0.000                      0.000               0.000                     0.000                  0.000                   -0.000                   0.000                               0.000                  0.000                       -0.000                         0.000                     0.000                      -2.799                0.000                     0.000     Online  55-64 years  Paid employment, part time or full time  Female                      -1.523
646                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  55-64 years                                  Retired    Male                       0.000
652                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN  In-person  65-74 years  Paid employment, part time or full time    Male                       0.000

## Age

In [22]:
manitoba_top_age = manitoba_table.groupby(manitoba_table['age']).emotional_engagement_score.mean().sort_values().head(3)

In [23]:
manitoba_top_age

age
55-64 years   -0.561
18-24 years   -0.429
25-34 years   -0.422
Name: emotional_engagement_score, dtype: float64

## Occupation

In [24]:
manitoba_top_occupation = manitoba_table.groupby(manitoba_table['occupation']).emotional_engagement_score.mean().sort_values().head(3)

In [25]:
manitoba_top_occupation

occupation
Prefer not to answer                      -0.829
Paid employment, part time or full time   -0.487
Retired                                   -0.483
Name: emotional_engagement_score, dtype: float64

## Channel

In [26]:
manitoba_top_channel = manitoba_table.groupby(manitoba_table['channel']).emotional_engagement_score.mean().sort_values().head(3)

In [27]:
manitoba_top_channel

channel
Online      -0.515
Telephone   -0.397
In-person   -0.329
Name: emotional_engagement_score, dtype: float64

# Peel

In [30]:
peel_table = summary_table.loc[summary_table['location']=='Peel']

In [31]:
column_list = ['channel', 'age', 'occupation', 'gender', 'emotional_engagement_score']

In [32]:
peel_table = peel_table[drivers_list+ column_list]

In [33]:
peel_table.dropna(axis=1, how='all', inplace=True)

In [34]:
peel_table

      drivers_positivity_score  drivers_security_score  drivers_convenience_score  drivers_care_score  drivers_timeliness_score  drivers_respect_score  drivers_knowledge_score  drivers_fairness_score  drivers_channel_satisfaction_score  drivers_outcome_score  drivers_communication_score  drivers_ease_of_access_score  drivers_competence_score  drivers_waiting_time_score  drivers_trust_score  drivers_innovative_score    channel          age                               occupation  gender  emotional_engagement_score
245                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN  Telephone  55-64 years                     Prefer not to answer  Female                       0.000
264                     -0.031                   0.000                     -0.033              -0.432                    -0.010                 -0.001                   -0.060                   0.000                              -0.001                 -0.042                       -0.016                        -0.001                    -1.325                      -0.001                0.000                     0.000  Telephone  55-64 years                                    Other    Male                      -0.778
290                      0.001                   0.000                      0.003               0.000                     0.006                  0.000                    0.000                   0.000                               0.008                  0.000                        0.000                         0.590                     0.000                       0.006                0.000                     0.000  In-person  35-44 years  Paid employment, part time or full time    Male                       0.077
361                      0.342                   0.000                      0.411               0.103                     0.006                  0.000                    0.000                   0.000                               0.162                  0.456                        0.001                         0.012                     0.000                       0.000                0.000                     0.000  In-person  45-54 years                                Homemaker  Female                       0.832
362                      0.342                   0.000                      0.411               0.103                     0.006                  0.000                    0.000                   0.000                               0.162                  0.456                        0.001                         0.012                     0.000                       0.000                0.000                     0.000  In-person  65-74 years                                  Retired  Female                       0.832
371                     -0.066                   0.000                     -0.176              -0.135                    -0.313                 -0.001                   -0.001                   0.000                              -0.037                 -0.168                       -0.670                        -0.001                    -0.001                      -0.002                0.000                    -0.000  Telephone  45-54 years  Paid employment, part time or full time    Male                      -0.279
388                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  35-44 years  Paid employment, part time or full time  Female                       0.000
409                     -0.017                   0.000                     -0.104              -0.011                    -0.039                  0.000                    0.000                   0.000                              -0.014                 -0.032                       -1.541                        -0.008                     0.000                       0.000                0.000                     0.000  In-person  35-44 years  Paid employment, part time or full time    Male                      -0.611
410                     -0.017                   0.000                     -0.104              -0.011                    -0.039                  0.000                    0.000                   0.000                              -0.014                 -0.032                       -1.541                        -0.008                     0.000                       0.000                0.000                     0.000  In-person  65-74 years                                  Retired    Male                      -0.611
422                     -0.093                  -0.056                     -0.075              -0.096                    -0.056                 -0.020                   -0.158                   0.000                              -0.038                 -0.041                       -0.172                        -0.076                    -0.001                      -1.094                0.000                    -0.085  Telephone  45-54 years  Paid employment, part time or full time    Male                      -0.897
423                     -0.093                  -0.056                     -0.075              -0.096                    -0.056                 -0.020                   -0.158                   0.000                              -0.038                 -0.041                       -0.172                        -0.076                    -0.001                      -1.094                0.000                    -0.085  In-person  65-74 years                                  Retired  Female                      -0.897
453                     -0.011                   0.000                     -0.120              -0.819                    -0.002                 -0.001                    0.000                  -1.210                               0.000                 -0.003                       -0.002                        -0.000                     0.000                      -0.019                0.000                     0.000     Online  45-54 years  Paid employment, part time or full time    Male                      -0.867
467                     -0.042                  -0.001                     -0.020              -0.202                    -0.003                 -1.739                   -0.018                   0.000                              -0.000                 -0.252                       -0.092                         0.000                    -0.017                      -0.003                0.000                     0.000  Telephone  55-64 years  Paid employment, part time or full time  Female                      -1.227
468                     -0.042                  -0.001                     -0.020              -0.202                    -0.003                 -1.739                   -0.018                   0.000                              -0.000                 -0.252                       -0.092                         0.000                    -0.017                      -0.003                0.000                     0.000     Online  35-44 years                                Homemaker  Female                      -1.227
470                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN  Telephone  65-74 years                                  Retired  Female                       0.000
491                     -0.005                   0.000                     -0.030              -0.004                     0.000                  0.000                   -1.638                   0.000                              -0.019                 -0.026                       -0.041                         0.000                     0.000                       0.000                0.000                     0.000  Telephone  65-74 years                                  Retired    Male                      -0.595
492                     -0.005                   0.000                     -0.030              -0.004                     0.000                  0.000                   -1.638                   0.000                              -0.019                 -0.026                       -0.041                         0.000                     0.000                       0.000                0.000                     0.000     Online  18-24 years               Student, full or part time    Male                      -0.595
532                      0.000                   0.000                      0.000               0.000                     0.000                  0.000                   -0.001                   0.000                               0.000                  0.000                        0.000                         0.000                     0.000                      -2.730                0.000                     0.000  Telephone  65-74 years  Paid employment, part time or full time    Male                      -1.530
533                      0.000                   0.000                      0.000               0.000                     0.000                  0.000                   -0.001                   0.000                               0.000                  0.000                        0.000                         0.000                     0.000                      -2.730                0.000                     0.000     Online  55-64 years                                  Retired    Male                      -1.530
555                     -0.059                   0.000                     -0.185              -0.051                    -0.272                  0.000                   -0.001                   0.000                              -0.034                 -0.045                       -1.010                        -0.044                    -0.000                      -0.004                0.000                     0.000  In-person  55-64 years                                  Retired  Female                      -0.556
572                      0.045                   0.000                      0.053               0.069                     0.004                  0.000                    0.000                   0.000                               0.030                  0.498                        0.092                         0.000                     0.000                       0.000                0.000                     0.000     Online  55-64 years  Paid employment, part time or full time    Male                       0.131
577                     -0.006                  -0.002                     -0.005              -0.066                    -0.096                  0.000                   -0.239                   0.000                              -0.025                 -0.017                       -1.364                        -0.000                     0.000                      -0.172                0.000                     0.000     Online  55-64 years                                  Retired    Male                      -0.801
583                     -0.006                   0.000                     -0.001              -0.500                     0.000                 -2.260                    0.000                   0.000                               0.000                 -0.012                        0.000                         0.000                     0.000                       0.000                0.000                     0.000     Online  45-54 years  Paid employment, part time or full time  Female                      -1.516
589                      0.008                   0.000                      0.003               0.018                     0.000                  0.000                    0.000                   0.000                               0.000                  0.155                        0.000                         0.000                     0.000                       0.000                0.000                     0.000  In-person  45-54 years  Paid employment, part time or full time    Male                       0.003
604                      0.079                   0.000                      0.048               0.019                     0.471                  0.000                    0.000                   0.000                               0.003                  0.039                        0.013                         0.000                     0.000                       0.001                0.000                     0.000     Online  45-54 years  Paid employment, part time or full time    Male                       0.040
605                      0.152                   0.000                      0.029               0.332                     0.005                  0.000                    0.000                   0.000                               0.000                  0.240                        0.000                         0.000                     0.000                       0.000                0.000                     0.000     Online  45-54 years  Paid employment, part time or full time  Female                       0.120
610                      0.085                   0.000                      0.095               0.259                     0.003                  0.000                    0.001                   0.000                               0.007                  0.800                        0.114                         0.000                     0.000                       0.000                0.000                     0.000  Telephone  55-64 years  Paid employment, part time or full time  Female                       0.572
621                      0.280                   0.000                      0.247               0.079                     0.049                  0.000                    0.000                   0.000                               0.002                  0.392                        0.000                         0.001                     0.000                       0.000                0.000                     0.000  Telephone  55-64 years  Paid employment, part time or full time  Female                       0.296
626                     -0.039                  -0.000                     -0.091              -0.059                    -2.174                 -0.008                   -0.001                   0.000                              -0.028                 -0.036                       -0.529                        -0.003                     0.000                      -0.126                0.000                     0.000     Online  45-54 years  Paid employment, part time or full time    Male                      -2.179
633                     -0.006                   0.000                     -0.010              -0.046                     0.000                 -0.023                   -0.000                   0.000                               0.000                 -0.007                       -0.036                         0.000                    -0.942                       0.000                0.000                     0.000  In-person  55-64 years  Paid employment, part time or full time    Male                      -0.206
638                     -0.159                  -0.000                     -0.096              -0.038                    -0.942                 -0.000                    0.000                   0.000                              -0.005                 -0.078                       -0.025                        -0.001                     0.000                      -0.002                0.000                     0.000  Telephone  25-34 years  Paid employment, part time or full time    Male                      -0.376
651                      0.000                   0.000                      0.000               0.000                     0.000                  0.000                    0.000                   0.000                               0.000                  0.000                        0.000                         0.000                     0.000                      -2.322                0.000                     0.000  In-person  55-64 years                                  Retired    Male                      -0.971
667                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  25-34 years  Paid employment, part time or full time  Female                       0.000
670                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  25-34 years  Paid employment, part time or full time    Male                       0.000
671                        NaN                     NaN                        NaN                 NaN                       NaN                    NaN                      NaN                     NaN                                 NaN                    NaN                          NaN                           NaN                       NaN                         NaN                  NaN                       NaN     Online  65-74 years                                  Retired    Male                       0.000
697                      0.003                   0.000                      0.006               0.012                     0.011                  0.000                    0.330                   0.000                               0.020                  0.015                        1.009                         0.000                     0.000                       0.001                0.000                     0.000     Online  45-54 years                         Looking for work  Female                       0.663
699                      0.014                   0.000                      0.012               0.181                     0.004                  0.006                    0.752                   0.000                               0.001                  0.033                        0.022                         0.001                     0.001                       0.042                0.000                     0.000  Telephone  55-64 years                                  Retired  Female                       0.386

## Age

In [35]:
peel_top_age = peel_table.groupby(peel_table['age']).emotional_engagement_score.mean().sort_values().head(3)

In [36]:
peel_top_age

age
45-54 years   -0.590
65-74 years   -0.493
35-44 years   -0.403
Name: emotional_engagement_score, dtype: float64

## Occupation

In [37]:
peel_top_occupation = peel_table.groupby(peel_table['occupation']).emotional_engagement_score.mean().sort_values().head(3)

In [38]:
peel_top_occupation

occupation
Prefer not to answer         -0.966
Other                        -0.592
Student, full or part time   -0.576
Name: emotional_engagement_score, dtype: float64

## Channel

In [39]:
peel_top_channel = peel_table.groupby(peel_table['channel']).emotional_engagement_score.mean().sort_values().head(3)

In [40]:
peel_top_channel

channel
Telephone   -0.511
Online      -0.352
In-person   -0.313
Name: emotional_engagement_score, dtype: float64